import { test, expect } from './fixtures.js';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { toolsTab, assetView } from './workspace-tools.js';

const assets = async (request, id) => (await (await request.get(`/fixtures/${id}`)).json()).assets;
const setup = async (request, id) => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0];

for (const narrow of [false, true]) test(`saved reel voice and combined character references (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }, testInfo) => {
  test.setTimeout(90000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`);
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  const file = testInfo.outputPath('voice-reel.mp4');
  execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=size=96x64:rate=24:duration=3',
    '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=32000:duration=3', '-c:v', 'libx264', '-threads', '1', '-c:a', 'aac', '-shortest', file]);
  const response = await request.post(`/fixtures/${id}/timeline-reel?lossless=false`, { data: readFileSync(file), headers: { 'Content-Type': 'video/mp4' } });
  expect(response.ok()).toBe(true); const { reel } = await response.json();
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  await page.goto(`/projects/${id}/assets`);
  const root = page.locator('.studio-workspace'); await expect(root).toHaveAttribute('data-ready', 'true');
  const drawer = root.locator('.workspace-right .workspace-drawer-heading [data-close-pane]');
  if (await drawer.isVisible()) await drawer.click();
  const open = async () => {
    await page.getByRole('button', { name: `Actions for ${reel.name}`, exact: true }).click();
    await page.getByRole('menuitem', { name: 'Save voice…', exact: true }).click();
    await expect(page.locator('.voice-dialog').getByRole('button', { name: 'Save voice reference', exact: true })).toBeEnabled();
  };
  await open();
  const voice = page.locator('.voice-dialog');
  await expect(voice.getByLabel('Make Juniper’s default voice')).not.toBeChecked();
  // The box sits on the line of its label, not above it.
  await expect.poll(() => voice.locator('label.media-details-check').evaluate(label => {
    const box = label.querySelector('input').getBoundingClientRect(), rect = label.getBoundingClientRect();
    return Math.round(Math.abs((box.top + box.height / 2) - (rect.top + rect.height / 2)));
  })).toBeLessThan(3);
  await expect(voice).toContainText('independent audio recording');
  await voice.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect((await assets(request, id)).voices).toHaveLength(0);
  await open();
  await voice.getByLabel('Recording name').fill('Elementalist voice');
  await voice.getByLabel('Start (seconds)', { exact: true }).fill('.5');
  await voice.getByLabel('End (seconds)', { exact: true }).fill('2.5');
  await voice.getByLabel('Make Juniper’s default voice').focus();
  await page.keyboard.press('Space');
  await expect(voice.getByLabel('Make Juniper’s default voice')).toBeChecked();
  await voice.getByRole('button', { name: 'Play excerpt', exact: true }).click();
  await expect.poll(() => voice.locator('audio').evaluate(a => a.currentTime)).toBeGreaterThanOrEqual(.5);
  await expect(voice.getByRole('button', { name: 'Save voice reference', exact: true })).toBeInViewport();
  await voice.getByRole('button', { name: 'Save voice reference', exact: true }).click();
  await expect(voice).not.toBeVisible();
  const library = await assets(request, id); const recording = library.voices[0];
  expect(library.assets[0].defaultVoiceId).toBe(recording.id); expect(recording.sourceReel.reelId).toBe(reel.id);
  await expect(page.locator('.media-look-badge').filter({ hasText: 'Default voice' })).toBeVisible();
  await page.reload(); await assetView(page, 'Reference reels');
  // The new reel's voice is part of its Prompt setup.
  await expect(async () => {
    if (!await page.locator('.workspace-right').isVisible()) await page.locator('[data-toggle-pane=right]').first().click({ timeout: 1000 });
    await expect(page.locator('.workspace-right')).toBeVisible();
  }).toPass({ timeout: 10000 });
  await page.locator('.reel-tools').getByRole('button', { name: 'Prompt', exact: true }).click();
  const reelVoice = page.locator('.reel-setup-dialog .reel-voice-options');
  if (!await reelVoice.evaluate(d => d.open)) await reelVoice.locator(':scope > summary').click();
  await expect(reelVoice.getByRole('combobox', { name: 'Voice mode', exact: true })).toHaveValue('ExistingRecording');
  await expect(reelVoice.getByRole('combobox', { name: 'Voice recording', exact: true })).toHaveValue(recording.id);
  await expect(reelVoice.getByRole('spinbutton', { name: 'Excerpt start', exact: true })).toHaveValue('0.5');
  await page.goto(`/projects/${id}/shots`); await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const refs = page.locator('.manual-reference-dialog');
  await refs.locator(`[data-reference="${library.assets[0].id}/${library.assets[0].images[0].id}"]`).click();
  await refs.locator(`[data-reel-id="${reel.id}"] .add-reel`).click();
  if (narrow) await refs.getByRole('tab', { name: /Selected references/ }).click();
  const row = refs.locator('.character-voice-row');
  await expect(row).toHaveCount(1); await expect(row).toContainText('Default · Elementalist voice');
  await expect(row).toContainText('<Audio 1>');
  await expect(refs.getByLabel('Use audio', { exact: true })).toHaveCount(0);
  await expect(row.getByLabel('Speaker for Juniper')).toHaveValue('JUNIPER');
  await row.getByLabel('Audio start for Juniper').fill('1');
  await row.getByLabel('Audio duration for Juniper').fill('1');
  await row.getByLabel('Voice for Juniper', { exact: true }).focus();
  await row.locator('audio').evaluate(a => a.play());
  await expect.poll(() => row.locator('audio').evaluate(a => a.currentTime)).toBeGreaterThanOrEqual(1);
  await expect(refs.locator('.manual-reference-footer')).toContainText('1/3 audio');
  await row.scrollIntoViewIfNeeded();
  await page.screenshot({ path: `artifacts/character-voice-manager-${narrow ? 'narrow' : 'desktop'}.png` });
  await request.post(`/fixtures/${id}/reference-save-failure?fail=true`);
  await refs.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(refs.getByRole('alert')).toContainText('Fixture storage unavailable');
  await expect(row.getByLabel('Audio start for Juniper')).toHaveValue('1');
  await request.post(`/fixtures/${id}/reference-save-failure?fail=false`);
  await refs.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(refs).not.toBeVisible();
  const saved = (await setup(request, id)).inputs;
  expect(saved.voices).toHaveLength(1); expect(saved.voices[0].voiceId).toBe(recording.id);
  expect(saved.voices[0].start).toBe(1); expect(saved.videos[0].useSoundtrack).toBe(false);
  expect(saved.characterVoices[0].fromDefault).toBe(true);
  if (narrow) await page.getByRole('button', { name: 'Close Shot tools', exact: true }).click();
  await page.locator('.shots-heading').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await setup(request, id)).inputs.voices.length).toBe(0);
  expect((await setup(request, id)).inputs.images).toHaveLength(0);
  expect((await setup(request, id)).inputs.videos).toHaveLength(0);
  await page.reload(); await toolsTab(page, 'References');
  expect((await setup(request, id)).inputs.characterVoices).toBeUndefined();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/character-voices-${narrow ? 'narrow' : 'desktop'}.png` });
});
