import { test, expect } from './fixtures.js';

test('per-model settings preserve defaults, drafts and return routes', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  const { slug } = await (await request.get(`/fixtures/${id}/project-route`)).json();
  const origin = `/projects/${slug}/assets?view=grid#focus`;
  const snapshot = async () => (await (await request.get('/fixtures/text-catalog')).json());
  const before = await snapshot();
  await page.setViewportSize({ width: 1173, height: 1272 });
  await page.goto(`/settings/ai?tab=text&provider=comfyui&returnUrl=${encodeURIComponent(origin)}`);
  await expect(page.locator('h1')).toBeFocused();
  const row = page.locator('.text-model-row').filter({ has: page.getByRole('button', { name: 'Mock script writer', exact: true }) });
  await row.getByRole('button', { name: 'Mock script writer', exact: true }).click();
  const form = row.getByRole('form', { name: 'Model generation settings' });
  await form.getByLabel('Maximum reply tokens', { exact: true }).fill('8192');
  await form.getByLabel('Model temperature', { exact: true }).fill('0.7');
  await row.getByLabel('Alias', { exact: true }).fill('Unsaved model alias');
  await page.getByRole('tablist', { name: 'Text model providers' }).getByRole('tab', { name: 'Defaults & profiles', exact: true }).click();
  await page.getByLabel('Text inactivity timeout in seconds', { exact: true }).fill('555');
  await page.getByRole('tablist', { name: 'Text model providers' }).getByRole('tab', { name: 'ComfyUI', exact: true }).click();
  await expect(form.getByLabel('Maximum reply tokens', { exact: true })).toHaveValue('8192');
  await form.getByRole('button', { name: 'Save model settings', exact: true }).click();
  await expect(page.getByText('Model generation settings saved.', { exact: true })).toBeVisible();
  const saved = await snapshot();
  expect(saved.defaultBackend).toBe(before.defaultBackend); expect(saved.comfyModel).toBe(before.comfyModel);
  expect(saved.textModelAliases).toEqual(before.textModelAliases);
  await expect(row.getByLabel('Alias', { exact: true })).toHaveValue('Unsaved model alias');
  await expect(row.getByRole('button', { name: 'Estimate capacity', exact: true })).toHaveCount(0);
  await form.getByLabel('Maximum reply tokens', { exact: true }).fill('12000');
  await form.getByRole('button', { name: 'Cancel model settings', exact: true }).click();
  await expect(form.getByLabel('Maximum reply tokens', { exact: true })).toHaveValue('8192');
  // The checkbox sits before its label rather than stretching across the form and squeezing the text into a column.
  const raise = form.getByRole('checkbox', { name: /Raise the reply limit/ });
  const [box, label] = [await raise.boundingBox(), await form.locator('.check-row').boundingBox()];
  expect(box.width).toBeLessThan(30); expect(label.height).toBeLessThan(60); expect(box.x - label.x).toBeLessThan(5);
  await row.scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/comfy-text-settings-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/comfy-text-settings-mobile.png', fullPage: true });
  await page.reload(); await expect(page.locator('h1')).toBeFocused();
  await expect(page.getByRole('link', { name: '← Back to assets' })).toHaveAttribute('href', origin);
  await row.getByRole('button', { name: 'Mock script writer', exact: true }).click();
  await expect(form.getByLabel('Maximum reply tokens', { exact: true })).toHaveValue('8192');
  await form.getByRole('button', { name: 'Use ComfyUI defaults', exact: true }).click();
  await expect(page.getByText('Model now uses ComfyUI defaults.', { exact: true })).toBeVisible();
});
