import { test, expect } from './fixtures.js';
import { openShotSetup, closeShotSetup } from './workspace-tools.js';

test.beforeEach(async ({ request }) => { await request.post('/fixtures/generation-setups/reset'); });

test('global generation presets follow shots and projects while prompts and references stay local', async ({ page, request, context }) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 1173, height: 1272 });
  const makeProject = async () => {
    const { id } = await (await request.get('/fixtures/new')).json();
    await request.post(`/fixtures/${id}/approved`);
    await request.post(`/fixtures/${id}/production-shot`);
    return id;
  };
  const id = await makeProject();
  await request.post(`/fixtures/${id}/production-shot`);
  await request.post(`/fixtures/${id}/images`);
  const setups = async project => (await (await request.get(`/fixtures/${project}/production`)).json()).compositions;
  const library = async () => (await request.get('/fixtures/generation-setups')).json();
  await page.goto(`/projects/${id}/shots`);
  await openShotSetup(page);
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await editor.fill('First shot only.');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const picker = page.locator('.manual-reference-dialog');
  await picker.locator('[data-reference]').first().click();
  await picker.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await openShotSetup(page, 'Generation settings');
  const dialog = page.locator('.shot-setup-dialog');
  await dialog.getByText('Setup options', { exact: true }).click();
  await dialog.getByRole('button', { name: 'New setup', exact: true }).click();
  await expect(dialog.getByLabel('Setup name', { exact: true })).toHaveValue('New setup');
  await dialog.getByLabel('Setup name', { exact: true }).fill('Seed Hunter');
  await dialog.getByText('Setup options', { exact: true }).click();
  await dialog.getByLabel('Default takes', { exact: true }).selectOption('4');
  await dialog.getByLabel('Default resolution', { exact: true }).selectOption('quick');
  await closeShotSetup(page);
  const preset = (await library()).setups.find(s => s.name === 'Seed Hunter');
  expect(preset.settings.takeCount).toBe(4);
  await page.locator('.shot-list-row').nth(1).click();
  await expect(page.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Seed Hunter');
  await openShotSetup(page);
  await expect(editor).toBeEmpty();
  await editor.fill('Second shot only.');
  await openShotSetup(page, 'Generation settings');
  await expect(dialog.getByLabel('Named setup', { exact: true })).toHaveValue(preset.id);
  await expect(dialog.getByLabel('Default takes', { exact: true })).toHaveValue('4');
  await closeShotSetup(page);
  const afterSecond = await setups(id);
  expect(afterSecond.filter(c => c.shotId === afterSecond[1].shotId).every(c => c.inputs.images.length === 0)).toBe(true);
  await page.locator('.shot-list-row').first().click();
  await openShotSetup(page);
  await expect(editor).toHaveText('First shot only.');
  await closeShotSetup(page);

  // Even a project created after selecting a preset starts with that selection.
  const otherId = await makeProject();
  await page.goto(`/projects/${otherId}/shots`);
  await expect(page.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Seed Hunter');
  await openShotSetup(page);
  await expect(editor).toBeEmpty();
  await editor.fill('Other project only.');
  await openShotSetup(page, 'Generation settings');
  await expect(dialog.getByLabel('Named setup', { exact: true })).toHaveValue(preset.id);
  await dialog.getByLabel('Default takes', { exact: true }).selectOption('2');
  await closeShotSetup(page);
  await expect.poll(async () => (await library()).setups.find(s => s.id === preset.id).settings.takeCount).toBe(2);
  await page.goto(`/projects/${id}/shots`);
  await openShotSetup(page, 'Generation settings');
  await expect(dialog.getByLabel('Default takes', { exact: true })).toHaveValue('2');
  await expect(dialog.getByText(/Shared across all shots and projects/)).toBeVisible();
  await page.screenshot({ path: 'artifacts/global-setup-settings-desktop.png', animations: 'disabled' });
  await closeShotSetup(page);
  await page.reload();
  await expect(page.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Seed Hunter');
  const separate = await context.newPage();
  await separate.goto(`/projects/${otherId}/shots`);
  await expect(separate.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Seed Hunter');
  await separate.close();
  const current = await setups(id);
  expect(current.filter(c => c.shotId === current[0].shotId).every(c => c.prompt === 'First shot only.' && c.inputs.images.length === 1)).toBe(true);
  expect(current.filter(c => c.shotId === current[1].shotId).every(c => c.prompt === 'Second shot only.' && c.inputs.images.length === 0)).toBe(true);
  await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect(page.locator('.shot-list-row')).toHaveCount(3);
  await expect(page.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Seed Hunter');
  await openShotSetup(page);
  await expect(editor).toBeEmpty();
  await closeShotSetup(page);
  await page.setViewportSize({ width: 390, height: 844 });
  await openShotSetup(page, 'Generation settings');
  await expect(dialog.getByLabel('Named setup', { exact: true })).toHaveValue(preset.id);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/global-setup-settings-phone.png', animations: 'disabled' });
  await closeShotSetup(page);
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});

test('the generation header switches setups from its menu and keeps their details in help', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`); await request.post(`/fixtures/${id}/production-shot`);
  await page.setViewportSize({ width: 1173, height: 900 });
  await page.goto(`/projects/${id}/shots`);
  // The setup's name is the dropdown that switches setups.
  const name = page.locator('.shot-setup-summary select.generation-preset-select option:checked');
  await expect(name).toHaveText('Default setup');
  await expect(page.getByText('Shared preset · across shots and projects')).toHaveCount(0);
  await page.getByRole('button', { name: 'Help: Generation setup', exact: true }).click();
  await expect(page.locator('.shot-setup-summary .help-hint-content')).toContainText('Shared across shots and projects');
  await page.keyboard.press('Escape');
  await openShotSetup(page, 'Generation settings');
  const dialog = page.locator('.shot-setup-dialog');
  await dialog.getByText('Setup options', { exact: true }).click();
  await dialog.getByRole('button', { name: 'New setup', exact: true }).click();
  await expect(dialog.getByLabel('Setup name', { exact: true })).toHaveValue('New setup');
  await dialog.getByLabel('Setup name', { exact: true }).fill('Night pass');
  await dialog.getByText('Setup options', { exact: true }).click();
  await closeShotSetup(page);
  await expect(name).toHaveText('Night pass');
  await page.getByRole('combobox', { name: 'Generation setup', exact: true }).selectOption({ label: 'Default setup' });
  await expect(name).toHaveText('Default setup');
  await openShotSetup(page, 'Generation settings');
  const library = await (await request.get('/fixtures/generation-setups')).json();
  await expect(dialog.getByLabel('Named setup', { exact: true })).toHaveValue(library.setups.find(s => s.name === 'Default setup').id);
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Edit generation preset', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Close generation preset', exact: true })).toBeVisible();
  await expect(dialog.getByLabel('Named setup', { exact: true })).toBeVisible();
});
