import { shotAction, generateTakes, composeProduction, closeShotSetup as closeSetup, toolsTab, compositionState } from './workspace-tools.js';
import { planningComposer, submitPlanning } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';

test('H3 LoRAs register, persist per shot, recover missing files and remain captured in takes and refinement', async ({ page, request }) => {
  test.setTimeout(150000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { id } = await (await request.get('/fixtures/new')).json();
  const state = () => compositionState(request, id);
  await request.post(`/fixtures/${id}/approved`);
  await page.goto(`/settings/ai?tab=loras&projectId=${id}&returnTo=shots`);
  await page.getByRole('button', { name: 'Refresh installed LoRAs', exact: true }).click();
  for (const [file, name, strength, trigger] of [
    ['h3/character.safetensors', 'H3 Mouse identity', '.75', 'juniper character'],
    ['h3/styles/film.safetensors', 'H3 film lighting', '1.2', ''],
  ]) {
    await page.getByRole('button', { name: 'Add registration', exact: true }).click();
    await expect(page.locator('#lora-file option').filter({ hasText: 'minimax_h3_ref2v_turbo' })).toHaveCount(0);
    await page.locator('#lora-file').selectOption(file);
    await page.locator('#lora-name').fill(name);
    await page.locator('#lora-workflow').selectOption('MiniMaxH3Ref2VA');
    await page.locator('#lora-default-strength').fill(strength);
    await page.locator('#lora-trigger').fill(trigger);
    await page.locator('#lora-tags').fill('sfw, h3');
    await page.getByRole('button', { name: 'Save LoRA library', exact: true }).click();
    await expect(page.locator('.lora-registration')).toHaveCount(0);
  }
  await page.locator('#lora-library-workflow').selectOption('MiniMaxH3Ref2VA');
  await expect(page.locator('.lora-library .lora-row')).toHaveCount(2);
  await page.getByRole('link', { name: /Back to shots/i }).click();
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const planning = page.locator('.shot-planning-dialog');
  await submitPlanning(page);
  await planning.getByRole('button', { name: 'Add reviewed shots' }).click();
  await page.getByLabel('Duration (seconds)').fill('1'); await page.getByLabel('Duration (seconds)').blur();
  await composeProduction(page);
  await toolsTab(page, 'Generate');
  const originalPrompt = await page.getByLabel('Action and camera').inputValue();
  const picker = page.locator('#lora-add');
  async function add(name) {
    await toolsTab(page, 'Generate');
    await picker.fill(name);
    await expect(page.getByRole('option').filter({ hasText: name })).toBeVisible();
    await picker.press('ArrowDown'); await picker.press('Enter');
    await expect(page.getByRole('checkbox', { name, exact: true })).toBeVisible();
  }
  await add('H3 Mouse identity'); await add('H3 film lighting');
  await expect(page.getByLabel('Action and camera')).toHaveValue(originalPrompt);
  await expect(page.getByRole('spinbutton', { name: 'Strength for H3 Mouse identity' })).toHaveValue('0.75');
  await page.getByRole('button', { name: 'Insert trigger into directing notes' }).click();
  await expect.poll(async () => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0].directingNotes).toContain('juniper character');
  await expect(page.getByLabel('Action and camera')).toHaveValue(originalPrompt);
  await page.getByRole('spinbutton', { name: 'Strength for H3 Mouse identity' }).fill('0.55');
  await page.getByRole('button', { name: 'Move H3 film lighting up' }).focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('checkbox', { name: 'H3 film lighting' })).toBeFocused();
  await expect.poll(async () => ((await state()).shots[0].loras ?? []).map(l => l.reference.fileName)).toEqual(['h3/styles/film.safetensors', 'h3/character.safetensors']);
  await page.reload(); await toolsTab(page, 'Generate');
  await expect(page.locator('.lora-selections')).not.toHaveAttribute('open');
  await page.screenshot({ path: 'artifacts/preset-loras-collapsed.png' });
  await page.locator('.lora-selections > summary').click();
  await expect(page.getByRole('spinbutton', { name: 'Strength for H3 Mouse identity' })).toHaveValue('0.55');
  await request.post('/fixtures/lora-file?file=h3%2Fcharacter.safetensors&missing=true');
  await page.getByRole('button', { name: 'Check video models' }).click();
  await expect(page.locator('.lora-row').filter({ hasText: 'H3 Mouse identity' })).toContainText('exact LoRA file is missing');
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeDisabled();
  await page.getByRole('checkbox', { name: 'H3 Mouse identity' }).uncheck();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await page.getByRole('checkbox', { name: 'H3 Mouse identity' }).check();
  await request.post('/fixtures/lora-file?file=h3%2Fcharacter.safetensors&missing=false');
  await page.getByRole('button', { name: 'Check video models' }).click();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await page.setViewportSize({ width: 390, height: 844 }); await toolsTab(page, 'Generate');
  await expect(picker).toBeVisible();
  const checkboxAlignment = await page.locator('.lora-row .check-row').first().evaluate(label => {
    const input = label.querySelector('input').getBoundingClientRect();
    const text = [...label.childNodes].find(n => n.nodeType === Node.TEXT_NODE && n.textContent.trim());
    const range = document.createRange(); range.selectNode(text); const words = range.getBoundingClientRect();
    return { beforeText: input.right <= words.left, verticalGap: Math.abs((input.top + input.bottom - words.top - words.bottom) / 2) };
  });
  expect(checkboxAlignment.beforeText).toBe(true); expect(checkboxAlignment.verticalGap).toBeLessThan(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/h3-loras-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await toolsTab(page, 'Generate');
  await page.getByRole('combobox', { name: 'Default takes', exact: true }).selectOption('2');
  await generateTakes(page);
  await expect(page.locator('.shot-setup-dialog')).toBeHidden();
  const review = page.locator('.shot-review-dialog');
  await expect(review).toBeVisible();
  await review.getByText('Applied LoRAs · 2', { exact: true }).click();
  await expect(review.locator('.video-lora-details')).toContainText('H3 Mouse identity');
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(2);
  const captured = (await state()).takes[0].snapshot.appliedLoras;
  expect(captured.map(l => l.strength)).toEqual([1.2, .55]);
  await review.getByRole('button', { name: 'One more take', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(3);
  expect((await state()).takes.every(t => JSON.stringify(t.snapshot.appliedLoras) === JSON.stringify(captured))).toBe(true);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Generate');
  await page.locator('.lora-selections > summary').click();
  await page.getByRole('checkbox', { name: 'H3 Mouse identity' }).uncheck();
  await expect.poll(async () => (await state()).shots[0].loras[1].enabled).toBe(false);
  await closeSetup(page);
  await page.getByRole('button', { name: 'Review latest batch', exact: true }).click();
  await review.locator('.take-quality-actions summary').click();
  await review.getByRole('button', { name: 'Improve quality', exact: true }).click();
  const form = review.getByRole('region', { name: 'Improve take quality' });
  await form.getByLabel('Output size').selectOption('0');
  await form.getByRole('button', { name: 'Queue Refine', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(4);
  const refined = (await state()).takes.find(t => t.refinement);
  expect(refined.snapshot.appliedLoras).toEqual(captured);
  await review.locator(`[data-shot-take="${refined.id}"]`).click();
  await expect(review.locator('.video-lora-details')).toContainText('Applied LoRAs · 2');
  await page.screenshot({ path: 'test-results/h3-loras-refinement.png', fullPage: true });
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await shotAction(page, 'Duplicate');
  await expect.poll(async () => (await state()).shots.length).toBe(2);
  await expect.poll(async () => (await state()).shots[1].loras).toEqual((await state()).shots[0].loras);
});

test('a shot keeps its own LoRAs beside its references, on top of the preset', async ({ page, request }) => {
  test.setTimeout(90000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await page.goto(`/settings/ai?tab=loras&projectId=${id}&returnTo=shots`);
  await page.getByRole('button', { name: 'Refresh installed LoRAs', exact: true }).click();
  await page.getByRole('button', { name: 'Add registration', exact: true }).click();
  await page.locator('#lora-file').selectOption('h3/character.safetensors');
  await page.locator('#lora-name').fill('H3 Mouse identity');
  await page.locator('#lora-workflow').selectOption('MiniMaxH3Ref2VA');
  await page.getByRole('button', { name: 'Save LoRA library', exact: true }).click();
  await expect(page.locator('.lora-registration')).toHaveCount(0);
  await page.getByRole('link', { name: /Back to shots/i }).click();
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  await submitPlanning(page);
  await page.locator('.shot-planning-dialog').getByRole('button', { name: 'Add reviewed shots' }).click();

  const section = page.locator('details.shot-loras');
  await expect(section.locator(':scope > summary')).toHaveText('LoRAs · 0 active');
  await section.locator(':scope > summary').click();
  const picker = page.locator('#shot-lora-add');
  await picker.fill('H3 Mouse identity');
  await expect(page.getByRole('option').filter({ hasText: 'H3 Mouse identity' })).toBeVisible();
  await picker.press('ArrowDown'); await picker.press('Enter');
  await expect(section.getByRole('checkbox', { name: 'H3 Mouse identity', exact: true })).toBeVisible();
  await expect(section.locator(':scope > summary')).toHaveText('LoRAs · 1 active');
  const production = async () => (await request.get(`/fixtures/${id}/production`)).json();
  await expect.poll(async () => ((await production()).shotContent[0].loras ?? []).map(l => l.reference.fileName)).toEqual(['h3/character.safetensors']);
  // The shared preset is untouched.
  expect((await compositionState(request, id)).shots[0].loras ?? []).toEqual([]);
  await page.reload();
  await expect(section.locator(':scope > summary')).toHaveText('LoRAs · 1 active');
  await section.locator(':scope > summary').click();
  await section.locator('.lora-selections > summary').click();
  await expect(section.getByRole('checkbox', { name: 'H3 Mouse identity', exact: true })).toBeChecked();
});
