import { generateTakes, toolsTab, compositionState } from './workspace-tools.js';
import { test, expect } from './fixtures.js';

test('upscaled previews retain choices, check setup, and publish native-size takes without refinement packages', async ({ page, request }) => {
  test.setTimeout(150000);
  page.setDefaultTimeout(15000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  await request.post(`/fixtures/${id}/take-generation-setup`);
  const { slug } = await (await request.get(`/fixtures/${id}/project-route`)).json();
  const state = () => compositionState(request, id);
  await page.goto(`/settings/ai?projectId=${id}&returnTo=shots`);
  await expect(page.locator('h1')).toBeFocused();
  await page.getByRole('tab', { name: 'Video models', exact: true }).click();
  // Upscaled preview is an add-on on the video models page.
  const setup = page.locator('[data-add-on=upscaled-preview]');
  await setup.locator('> summary').click();
  await expect(setup.locator('> summary .video-status')).toHaveText('Ready');
  const file = setup.locator('[data-requirement=upscaler-file]');
  await expect(file.locator('.video-status')).toHaveText('Other file');
  await setup.getByLabel('Latent upscaler checkpoint file', { exact: true }).selectOption('mock-h3-3d.safetensors');
  await page.getByRole('button', { name: 'Save video models', exact: true }).click();
  await expect(page.getByText('Video models saved.', { exact: true })).toBeVisible();
  await expect(setup.locator('> summary .video-status')).toHaveText('Ready');
  await request.post('/fixtures/video-companion?available=false');
  await page.getByRole('link', { name: /Back to shots/i }).click();
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate');
  await page.getByRole('combobox', { name: 'Default takes', exact: true }).selectOption('1');
  const resolution = page.getByLabel('Default resolution', { exact: true });
  await expect(resolution.locator('option')).toHaveText(['Quick · 0.2 MP · 608 × 352', 'Preview · 0.4 MP · 832 × 480', 'Detail · 0.7 MP · 1120 × 640', 'Native · 1 MP · 1344 × 768', 'Upscaled preview']);
  await expect(resolution).toHaveValue('preview');
  await resolution.selectOption('upscaled');
  await expect(page.getByText(/832 × 480 sampling → 1344 × 768 output/)).toBeVisible();
  await expect.poll(async () => (await state()).shots[0].upscalePreview).toBe(true);
  await page.reload();
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate'); await expect(resolution).toHaveValue('upscaled');
  await request.post('/fixtures/video-upscaler?available=false');
  await page.getByRole('button', { name: 'Check video models', exact: true }).click();
  await expect(resolution).toHaveValue('upscaled');
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeDisabled();
  const setupLink = new URL(await page.getByRole('link', { name: 'Set up preview upscaling', exact: true }).getAttribute('href'), page.url());
  expect(setupLink.searchParams.get('tab')).toBe('video');
  expect(setupLink.searchParams.get('returnUrl')).toBe(`/projects/${slug}/shots`);
  await resolution.selectOption('preview');
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await resolution.selectOption('upscaled');
  await request.post('/fixtures/video-upscaler?available=true');
  await request.post('/fixtures/video-companion?available=false');
  await page.getByRole('button', { name: 'Check video models', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await page.setViewportSize({ width: 390, height: 844 }); await toolsTab(page, 'Generate');
  await expect(resolution).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/h3-preview-upscaling-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await toolsTab(page, 'Generate');
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog'); await expect(review).toBeVisible();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(1);
  let take = (await state()).takes[0];
  expect([take.width, take.height]).toEqual([1344, 768]); expect(take.refinementPackage).toBeNull();
  expect(take.snapshot.captureRefinementData).toBe(false); expect(take.snapshot.previewUpscale.implementation).toBe(1); // Plus, using the existing numeric API enum format.
  await review.getByText('Performance and timings', { exact: true }).click();
  await expect(review.getByText('Upscaling', { exact: true })).toBeVisible();
  await review.getByText('Captured profile', { exact: true }).click();
  await expect(review.getByText(/Upscaled preview · 832 × 480 → 1344 × 768/)).toBeVisible();
  await page.screenshot({ path: 'test-results/h3-preview-upscaling-desktop.png', fullPage: true });
  await review.getByRole('button', { name: 'One more take', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(2);
  expect((await state()).takes[1].snapshot.previewUpscale).toEqual(take.snapshot.previewUpscale);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Generate');
  await resolution.selectOption('native');
  await expect.poll(async () => (await state()).shots[0].nativeResolution).toBe(true);
  expect((await state()).shots[0].upscalePreview ?? false).toBe(false);
  await request.post('/fixtures/video-companion?available=true');
});
