import { planningComposer, submitPlanning } from './text-assistance-tools.js';
import { generateTakes, composeProduction, toolsTab, compositionState } from './workspace-tools.js';
import { test, expect } from './fixtures.js';

test('presets, setup and optional archives survive autosave and queue capture', async ({ page, request }) => {
  test.setTimeout(100000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  const state = () => compositionState(request, id);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const planning = page.locator('.shot-planning-dialog');
  await submitPlanning(page);
  await planning.getByRole('button', { name: 'Add reviewed shots' }).click();
  await page.getByLabel('Duration (seconds)').fill('1'); await page.getByLabel('Duration (seconds)').blur();
  await composeProduction(page);
  await toolsTab(page, 'Generate');
  const preset = page.getByRole('combobox', { name: 'Generation preset', exact: true });
  const archive = page.getByLabel('Save lossless frames', { exact: true });
  await expect(preset.locator('option')).toHaveCount(10);
  expect(await preset.locator('option').evaluateAll(nodes => nodes.map(n => n.value))).toEqual(['standard', 'beta', 'euler-beta', 'larry', 'pdd', 'spectrum', 'turbo4', 'turbo4-075', 'turbo8', 'hyperflow']);
  await expect(preset).toHaveValue('standard'); await expect(archive).not.toBeChecked();
  await preset.selectOption('larry');
  await expect.poll(async () => (await state()).shots[0].generationPreset).toBe('larry');
  await request.post('/fixtures/video-preset?key=larry&available=false');
  {
    await page.getByRole('button', { name: 'Check video models', exact: true }).click();
    await expect(preset).toHaveValue('larry');
    await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeDisabled();
    await page.getByRole('link', { name: 'Preset setup and video models' }).click();
    await page.getByRole('button', { name: 'Refresh video models', exact: true }).click();
    const row = page.locator('[data-preset=larry]');
    await expect(row).toContainText('Setup needed'); await row.locator('summary').click();
    await expect(row.getByRole('link', { name: /Larry Turbo/ })).toBeVisible();
    await expect(row.getByRole('link', { name: 'v4 step600 EMA' })).toBeVisible();
    await expect(page.getByRole('link', { name: /Back to shots/ })).toHaveAttribute('href', `/projects/${(await (await request.get(`/fixtures/${id}/project-route`)).json()).slug}/shots`);
    await page.getByRole('link', { name: /Back to shots/ }).click();
  }
  await request.post('/fixtures/video-preset?key=larry&available=true');
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate');
  await page.getByRole('button', { name: 'Check video models', exact: true }).click();
  await expect(preset).toHaveValue('larry');
  await page.setViewportSize({ width: 390, height: 844 }); await toolsTab(page, 'Generate');
  await expect(archive).toBeVisible();
  await expect(archive).not.toBeChecked();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/h3-presets-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await toolsTab(page, 'Generate');
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog'); await expect(review).toBeVisible();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(1);
  const first = (await state()).takes[0];
  expect(first.frames).toHaveLength(0); expect(first.snapshot.preset.key).toBe('larry');
  expect(first.snapshot.outputPolicy.saveLosslessFrames).toBe(false);
  await expect(review.getByText(/Frames are extracted from compressed MP4/)).toBeVisible();
  await expect(review.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeEnabled();
  await review.getByText('Performance and timings', { exact: true }).click();
  await expect(review.getByText('Not requested', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/h3-presets-desktop.png', fullPage: true });
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Generate'); await archive.check(); await preset.selectOption('pdd');
  await expect.poll(async () => (await state()).shots[0].saveLosslessFrames).toBe(true);
  await expect.poll(async () => (await state()).shots[0].generationPreset).toBe('pdd');
  await page.reload(); await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate'); await expect(archive).toBeChecked(); await expect(preset).toHaveValue('pdd');
  await generateTakes(page);
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(2);
  const archived = (await state()).takes.find(t => t.snapshot.preset.key === 'pdd');
  expect(archived.frames.length).toBe(archived.snapshot.frameCount);
});
