import { test, expect } from './fixtures.js';
import { toolsTab, openShotSetup, closeShotSetup } from './workspace-tools.js';

for (const narrow of [false, true]) test(`review a prompt before setting duration (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  const shots = async () => (await (await request.get(`/fixtures/${id}/shots`)).json()).shots;
  const composition = async () => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0];
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  const add = page.getByRole('button', { name: '+ Shot', exact: true });
  if (!await add.isVisible()) await page.locator('[data-toggle-pane=left]').click();
  await add.click();
  await page.getByLabel('Shot title', { exact: true }).fill('Production test');
  await expect(page.getByRole('combobox', { name: 'Scene', exact: true })).not.toHaveValue('');
  await page.getByLabel('Action and camera', { exact: true }).fill('A quiet morning. Keep the camera still.');
  await openShotSetup(page);
  await page.getByLabel('H3 prompt', { exact: true }).fill(Array.from({ length: 12 }, (_, index) => `Beat ${index + 1}: She looks out of the window, then returns to her desk. Keep the camera still.`).join('\n\n'));
  await closeShotSetup(page);
  const original = await composition();
  const duration = page.getByLabel('Duration (seconds)', { exact: true });
  await expect.poll(async () => (await shots())[0].duration ?? null).toBe(null);
  const review = page.getByRole('button', { name: 'Review prompt for shot 1: Production test', exact: true });
  const closeTools = page.getByRole('button', { name: 'Close Shot tools', exact: true });
  if (await closeTools.isVisible()) await closeTools.click();
  if (!await review.isVisible()) await page.locator('[data-toggle-pane=left]').click();
  await review.click();
  const dialog = page.locator('.shot-setup-dialog');
  const accept = dialog.getByRole('button', { name: 'Mark reviewed', exact: true });
  await expect(dialog).toContainText('You can review the prompt now.');
  await expect(accept).toBeEnabled();
  await expect(accept).toBeInViewport();
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/prompt-review-${narrow ? 'narrow' : 'desktop'}.png` });
  await accept.click();
  await expect(accept).toBeDisabled();
  await expect(dialog).toContainText('Prompt reviewed against the current shot and references.');
  await expect.poll(async () => (await composition()).acceptedRevisionId).not.toBeNull();
  const accepted = await composition();
  expect(accepted.prompt).toBe(original.prompt);
  expect(accepted.history.find(r => r.id === accepted.acceptedRevisionId).prompt).toBe(original.prompt);
  expect((await shots())[0].duration ?? null).toBeNull();
  expect((await (await request.get('/fixtures/ai-jobs')).json()).filter(j => j.target.projectId === id)).toHaveLength(0);
  await dialog.getByRole('button', { name: 'Set duration', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(duration).toBeFocused();
  await expect(duration).toBeInViewport();
  await toolsTab(page, 'References');
  const footer = page.locator('.shot-controls > .workspace-pane-footer');
  await expect(footer.getByRole('button', { name: 'Generate takes', exact: true })).toBeDisabled();
  await expect(footer.getByRole('button', { name: 'Review prompt', exact: true })).toHaveCount(0);
  // A reviewed prompt is not the next step; the missing duration is.
  const prompt = footer.getByRole('button', { name: 'Prompt', exact: true });
  await expect(prompt).not.toHaveClass(/next-step/);
  await footer.getByRole('button', { name: 'Set duration', exact: true }).click();
  await expect(duration).toBeFocused();
  await duration.fill('1'); await duration.blur();
  await expect.poll(async () => (await shots())[0].duration).toBe(1);
  await toolsTab(page, 'References');
  await expect(footer.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  // The new duration changes the shot, so Prompt asks for review again and says why, though Generate stays available.
  await expect(prompt).toContainText('Review prompt');
  await expect(prompt).toHaveClass(/next-step stale/);
  await expect(footer.locator('.prompt-stale-note')).toHaveText('The shot changed since this prompt was reviewed. Review it, or revise it with AI, before generating.');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});

test('the outline review action selects the requested shot and opens its prompt', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  await request.post(`/fixtures/${id}/take-generation-setup`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect(page.locator('.shot-list-row')).toHaveCount(2);
  await expect(page.locator('.shot-list-row').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Review prompt for shot 1: Production test', exact: true }).click();
  await expect(page.locator('.shot-setup-dialog')).toBeVisible();
  await expect(page.getByLabel('H3 prompt', { exact: true })).toContainText('subject_definitions:');
  await closeShotSetup(page);
  await expect(page.locator('.shot-list-row').first()).toHaveAttribute('aria-pressed', 'true');
});
