import { test, expect } from './fixtures.js';
import { openShotSetup, closeShotSetup } from './workspace-tools.js';

test('reels share named presets with shots while keeping output overrides and look drafts', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  await request.post(`/fixtures/${id}/planning-looks`);
  const assets = async () => (await (await request.get(`/fixtures/${id}`)).json()).assets;
  const presets = async () => (await (await request.get('/fixtures/generation-setups')).json()).setups;
  const owner = (await assets()).assets.find(a => a.looks.length === 2);
  await page.setViewportSize({ width: 1152, height: 1244 });
  await page.goto(`/projects/${id}/shots`);
  await openShotSetup(page, 'Generation settings');
  const shotEditor = page.locator('.shot-setup-dialog');
  await shotEditor.getByText('Setup options', { exact: true }).click();
  await shotEditor.getByRole('button', { name: 'New setup', exact: true }).click();
  await expect(shotEditor.getByLabel('Setup name', { exact: true })).toHaveValue('New setup');
  await shotEditor.getByLabel('Setup name', { exact: true }).fill('Shared reel preset');
  await shotEditor.getByText('Setup options', { exact: true }).click();
  await shotEditor.getByLabel('Default takes', { exact: true }).selectOption('3');
  await shotEditor.getByLabel('Default resolution', { exact: true }).selectOption('quick');
  await closeShotSetup(page);
  const preset = (await presets()).find(s => s.name === 'Shared reel preset');

  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
  const tools = page.locator('.reel-tools');
  const editor = page.locator('.reel-setup-dialog');
  await expect(tools.locator('select.generation-preset-select option:checked')).toHaveText(preset.name);
  await expect(tools.getByLabel('Reel takes', { exact: true })).toHaveValue('3');
  await expect(tools.getByLabel('Reel resolution', { exact: true })).toHaveValue('quick');
  await expect(page.locator('.compact-creation-header .asset-tool-context strong')).toHaveCount(0);
  await tools.getByLabel('Reel takes', { exact: true }).selectOption('2');
  await tools.getByLabel('Reel resolution', { exact: true }).selectOption('detail');
  await tools.getByRole('button', { name: 'Prompt', exact: true }).click();
  await expect(editor.locator('[data-prompt-ready]')).toHaveAttribute('data-prompt-ready', 'true');
  await editor.getByRole('textbox', { name: 'H3 prompt', exact: true }).fill('Keep my general reel prompt.');
  await editor.getByRole('button', { name: 'Done', exact: true }).click();
  await tools.getByRole('button', { name: 'Edit reel preset' }).click();
  await expect(editor.getByLabel('Named setup', { exact: true })).toHaveValue(preset.id);
  await editor.getByLabel('Default takes', { exact: true }).selectOption('4');
  await editor.getByLabel('Generation preset', { exact: true }).selectOption('turbo4');
  await expect.poll(async () => (await presets()).find(s => s.id === preset.id).settings.takeCount).toBe(4);
  await editor.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(tools.getByLabel('Reel takes', { exact: true })).toHaveValue('2');
  await expect(tools.getByLabel('Reel resolution', { exact: true })).toHaveValue('detail');

  await tools.getByLabel('Reel look', { exact: true }).selectOption(owner.looks[0].id);
  await tools.getByRole('button', { name: 'Prompt', exact: true }).click();
  await expect(editor.getByRole('textbox', { name: 'H3 prompt', exact: true })).toBeEmpty();
  await editor.getByRole('textbox', { name: 'H3 prompt', exact: true }).fill('Keep my look-specific reel prompt.');
  await editor.getByRole('button', { name: 'Done', exact: true }).click();
  await tools.getByLabel('Reel look', { exact: true }).selectOption('');
  await tools.getByRole('button', { name: 'Prompt', exact: true }).click();
  await expect(editor.getByRole('textbox', { name: 'H3 prompt', exact: true })).toHaveText('Keep my general reel prompt.');
  await editor.getByRole('button', { name: 'Done', exact: true }).click();
  await tools.getByRole('combobox', { name: 'Generation setup', exact: true }).selectOption({ label: 'Default setup' });
  await expect(tools.locator('select.generation-preset-select option:checked')).toHaveText('Default setup');
  await expect(tools.getByLabel('Reel takes', { exact: true })).toHaveValue('2');
  // A reload does not wait for the choice to be saved, so wait for that first.
  await expect.poll(async () => (await assets()).reelDrafts.find(d => d.assetId === owner.id && !d.lookId)?.generationSetup?.name).toBe('Default setup');
  await page.reload();
  await expect(tools.locator('select.generation-preset-select option:checked')).toHaveText('Default setup');
  await page.screenshot({ path: 'artifacts/reel-named-preset-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-toggle-pane=right]').click();
  await expect(tools.getByLabel('Reel look', { exact: true })).toBeInViewport();
  expect(await tools.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/reel-named-preset-mobile.png' });
  await page.setViewportSize({ width: 1152, height: 1244 });
  await page.goto(`/projects/${id}/shots`);
  await page.getByRole('combobox', { name: 'Generation setup', exact: true }).selectOption({ label: preset.name });
  await openShotSetup(page, 'Generation settings');
  await expect(shotEditor.getByLabel('Default takes', { exact: true })).toHaveValue('4');
  await expect(shotEditor.getByLabel('Generation preset', { exact: true })).toHaveValue('turbo4');
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});
