import { test, expect } from './fixtures.js';

const library = async (request, id) => (await (await request.get(`/fixtures/${id}`)).json()).assets;
for (const [mode, narrow, environment] of [['RefMod', false, false], ['RefMod', true, true], ['FullReel', false, true]]) {
  test(`generate a ${environment ? 'setting' : 'character'} reel using ${mode} (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
    test.setTimeout(120000);
    page.setDefaultTimeout(15000);
    const { id } = await (await request.get('/fixtures/new')).json();
    await request.post(`/fixtures/${id}/images`);
    if (environment) await request.post(`/fixtures/${id}/environment-reel-owner`);
    expect((await request.post(`/fixtures/${id}/regeneration-source`)).ok()).toBe(true);
    await expect.poll(async () => (await library(request, id)).reels.length, { timeout: 45000 }).toBe(1);
    expect((await request.post(`/fixtures/${id}/reel-reference-default?mode=${mode}`)).ok()).toBe(true);
    const initial = await library(request, id), source = initial.reels[0], owner = initial.assets[0];
    await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
    await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
    await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
    await expect(page.locator('.workspace-right')).toBeVisible();
    const tools = page.locator('.reel-tools');
    const manager = page.getByRole('dialog', { name: 'Reel references', exact: true });
    await tools.getByRole('button', { name: 'Manage references', exact: true }).click();
    await manager.getByRole('combobox', { name: 'Reference type', exact: true }).selectOption('Reels');
    await manager.locator(`[data-reel-id='${source.id}'] .add-reel`).click();
    if (narrow) await manager.getByRole('tab', { name: /^Selected references/ }).click();
    await expect(manager.getByLabel('Visuals', { exact: true })).toHaveValue(mode);
    await expect(manager.getByLabel('Use audio', { exact: true })).toHaveCount(0);
    await manager.getByLabel('Visuals', { exact: true }).selectOption('Keyframes');
    await manager.getByRole('button', { name: 'Use asset default', exact: true }).click();
    await expect(manager.getByLabel('Visuals', { exact: true })).toHaveValue(mode);
    await manager.getByRole('button', { name: 'Apply changes', exact: true }).click();
    await expect(manager).not.toBeVisible();
    const modeValue = mode === 'RefMod' ? 3 : 0;
    const draft = () => library(request, id).then(l => l.reelDrafts.at(-1));
    await expect.poll(async () => (await draft()).keyframeReels?.[0].visuals).toBe(modeValue);
    const saved = await draft();
    expect(saved.images).toHaveLength(0);
    expect(saved.keyframeReels[0].useSoundtrack).toBe(false);
    if (mode === 'RefMod') expect(saved.keyframeReels[0].refMod.recipe.frameHashes).toHaveLength(3);
    // Changing the asset default must not reinterpret this saved selection.
    expect((await request.post(`/fixtures/${id}/reel-reference-default?mode=Keyframes`)).ok()).toBe(true);
    await page.reload();
    await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
    await expect(tools.locator('.shot-reference-counts')).toContainText('Reels 1');
    const reelTile = tools.getByRole('button', { name: `Preview reel ${source.name}`, exact: true });
    await expect(reelTile).toBeVisible();
    await expect.poll(() => reelTile.locator('img').evaluate(img => img.naturalWidth)).toBeGreaterThan(0);
    await reelTile.click();
    await expect(page.getByLabel('Reference video playback', { exact: true })).toHaveAttribute('src', new RegExp(`/reference-videos/${source.media.id}$`));
    await page.getByRole('button', { name: 'Close video preview', exact: true }).click();
    await tools.getByRole('button', { name: 'Manage references', exact: true }).click();
    if (narrow) await manager.getByRole('tab', { name: /^Selected references/ }).click();
    await manager.locator('.video-reference-list .reference-settings-button').click();
    await expect(manager.getByLabel('Visuals', { exact: true })).toHaveValue(mode);
    await manager.getByLabel('Visuals', { exact: true }).selectOption('Keyframes');
    await manager.getByRole('button', { name: 'Cancel', exact: true }).click();
    expect((await draft()).keyframeReels[0].visuals).toBe(modeValue);

    await tools.getByRole('button', { name: 'Prompt', exact: true }).click();
    await page.locator('.reel-setup-dialog').getByRole('button', { name: 'Reel assistance', exact: true }).click();
    const assist = page.getByRole('dialog', { name: 'Reel assistance', exact: true });
    await assist.locator('.model-chip').click();
    await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption({ label: 'OpenRouter · Alternate mock model' });
    await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
    await assist.getByRole('button', { name: 'Compose pair', exact: true }).click();
    await expect(assist).not.toBeVisible();
    await expect(page.locator('.reel-setup-dialog').getByRole('textbox', { name: 'H3 prompt', exact: true })).toContainText('<Video 1>', { timeout: 25000 });
    await expect(page.locator('.reel-setup-dialog').getByRole('textbox', { name: 'H3 prompt', exact: true })).not.toContainText('<Picture');
    const compositions = (await (await request.get('/fixtures/reel-compositions')).json());
    expect(compositions).toHaveLength(1);
    expect(compositions[0].images).toHaveLength(mode === 'RefMod' ? 3 : 0);
    expect(compositions[0].context.videoReferences.videos[0].representation).toBe(mode);
    await page.screenshot({ path: `artifacts/reel-visual-${mode}-${narrow ? 'narrow' : 'desktop'}.png` });
    await page.locator('.reel-setup-dialog').getByRole('button', { name: 'Done', exact: true }).click();
    await tools.getByRole('button', { name: 'Generate reel', exact: true }).click();
    await expect.poll(async () => (await library(request, id)).reels.length, { timeout: 45000 }).toBe(2);
    const generated = (await library(request, id)).reels.find(r => r.id !== source.id);
    expect(generated.generation.recipe.keyframeReels[0].visuals).toBe(modeValue);
    const captured = await (await request.get(`/fixtures/ai-jobs/${generated.generation.jobId}/video-inputs`)).json();
    expect(captured.inputs.map(i => i.kind)).toEqual(mode === 'RefMod' ? [] : ['Video']);
    if (mode === 'RefMod') expect(JSON.stringify(captured.graph)).toContain('RefMod');
    const review = tools.getByRole('button', { name: 'Review latest batch', exact: true });
    const generate = tools.getByRole('button', { name: 'Generate reel', exact: true });
    await expect(review).toHaveText('Review');
    const [generateBounds, reviewBounds] = await Promise.all([generate.boundingBox(), review.boundingBox()]);
    expect(Math.abs(generateBounds.y - reviewBounds.y)).toBeLessThan(2);
    expect(reviewBounds.x).toBeGreaterThan(generateBounds.x);
    expect(reviewBounds.width).toBeLessThan(generateBounds.width);
    await review.click();
    const batch = page.getByRole('dialog', { name: 'Reference reel request', exact: true });
    await expect(batch.locator('video')).toHaveAttribute('src', new RegExp(`/reference-videos/${generated.media.id}$`));
    await batch.getByRole('button', { name: 'Close', exact: true }).click();
    await expect(review).toBeFocused();
    await page.screenshot({ path: `artifacts/reel-footer-${mode}-${narrow ? 'narrow' : 'desktop'}.png` });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  });
}

test('reel references opened while the recipe starts fresh edit the fresh recipe', async ({ page, request }) => {
  test.setTimeout(100000);
  page.setDefaultTimeout(15000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`);
  await request.post(`/fixtures/${id}/environment-reel-owner`);
  expect((await request.post(`/fixtures/${id}/regeneration-source`)).ok()).toBe(true);
  await expect.poll(async () => (await library(request, id)).reels.length, { timeout: 45000 }).toBe(1);
  expect((await request.post(`/fixtures/${id}/reel-reference-default?mode=FullReel`)).ok()).toBe(true);
  const initial = await library(request, id), source = initial.reels[0], owner = initial.assets[0], finished = initial.reelDrafts[0];
  expect(finished.images).toHaveLength(1);
  // Opening the page starts a fresh recipe; hold that save so the dialog opens during it.
  expect((await request.post('/fixtures/reel-fresh-delay?milliseconds=1500')).ok()).toBe(true);
  await page.setViewportSize({ width: 1173, height: 1000 });
  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  const tools = page.locator('.reel-tools');
  const manager = page.getByRole('dialog', { name: 'Reel references', exact: true });
  await tools.getByRole('button', { name: 'Manage references', exact: true }).click();
  await manager.getByRole('combobox', { name: 'Reference type', exact: true }).selectOption('Reels');
  await manager.locator(`[data-reel-id='${source.id}'] .add-reel`).click();
  await manager.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(manager).not.toBeVisible();
  await expect(tools.locator('.shot-reference-counts')).toContainText('Images 0/9Reels 1Audio 0/3');
  const drafts = (await library(request, id)).reelDrafts;
  expect(drafts).toHaveLength(2);
  expect(drafts.at(-1).id).not.toBe(finished.id);
  expect(drafts.at(-1).images).toHaveLength(0);
  expect(drafts.at(-1).keyframeReels).toHaveLength(1);
  expect(drafts.find(d => d.id === finished.id).images).toHaveLength(1);
});
