import { test, expect } from './fixtures.js';
const library = async (request, id) => (await (await request.get(`/fixtures/${id}`)).json()).assets;
for (const narrow of [false, true]) test(`use another reel's keyframes as pictures (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  test.setTimeout(100000);
  page.setDefaultTimeout(15000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`);
  if (!narrow) await request.post(`/fixtures/${id}/environment-reel-owner`);
  expect((await request.post(`/fixtures/${id}/regeneration-source`)).ok()).toBe(true);
  await expect.poll(async () => (await library(request,id)).reels.length, {timeout:45000}).toBe(1);
  const initial = await library(request,id), source = initial.reels[0], owner = initial.assets[0];
  await page.setViewportSize({width:narrow?390:1173,height:narrow?844:1000});
  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready','true');
  await expect(page.locator('.workspace-right')).toBeVisible();
  const tools = page.locator('.reel-tools');
  await tools.getByRole('button',{name:'Manage references',exact:true}).click();
  const manager = page.getByRole('dialog',{name:'Reel references',exact:true});
  await manager.getByRole('combobox',{name:'Reference type',exact:true}).selectOption('Reels');
  await manager.locator(`[data-reel-id='${source.id}'] .add-reel`).click();
  await expect(manager.locator('[data-video-reference-id]')).toHaveCount(1);
  if (narrow) await manager.getByRole('tab',{name:/^Selected references/}).click();
  await expect(manager.getByLabel('Visuals',{exact:true})).toHaveValue('Keyframes');
  await expect(manager.getByLabel('Use audio',{exact:true})).toHaveCount(0);
  await manager.getByRole('button',{name:'Manage keyframes…',exact:true}).click();
  const frames=page.locator('.keyframe-editor');
  await expect(frames.getByRole('button',{name:'Add current frame',exact:true})).toBeEnabled();
  await frames.getByRole('button',{name:'Add current frame',exact:true}).click();
  await expect(frames.locator('.keyframe-list > li')).toHaveCount(1);
  await frames.getByLabel('Frame notes (optional)').fill('Keep the visible blue material.');
  await frames.getByRole('button',{name:'Apply keyframes',exact:true}).click();
  await expect(frames).not.toBeVisible();
  await manager.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(manager).not.toBeVisible();
  const draft = () => library(request,id).then(l=>l.reelDrafts.at(-1));
  expect((await draft()).keyframeReels ?? []).toHaveLength(0);
  await tools.getByRole('button',{name:'Manage references',exact:true}).click();
  await manager.getByRole('combobox',{name:'Reference type',exact:true}).selectOption('Reels');
  await manager.locator(`[data-reel-id='${source.id}'] .add-reel`).click();
  await expect(manager.locator('[data-video-reference-id]')).toHaveCount(1);
  if (narrow) await manager.getByRole('tab',{name:/^Selected references/}).click();
  await manager.getByRole('button',{name:'Manage keyframes…',exact:true}).click();
  await expect(frames.getByRole('button',{name:'Add current frame',exact:true})).toBeEnabled();
  await frames.getByRole('button',{name:'Add current frame',exact:true}).click();
  await expect(frames.locator('.keyframe-list > li')).toHaveCount(1);
  await frames.getByLabel('Frame notes (optional)').fill('Keep the visible blue material.');
  await frames.getByRole('button',{name:'Apply keyframes',exact:true}).click();
  const apply=manager.getByRole('button',{name:'Apply changes',exact:true});
  await apply.focus(); await expect(apply).toBeInViewport();
  await page.screenshot({path:`artifacts/reel-picture-inputs-${narrow?'narrow':'desktop'}.png`});
  await apply.press('Enter'); await expect(manager).not.toBeVisible();
  await expect.poll(async()=>(await draft()).keyframeReels?.length).toBe(1);
  const saved=await draft();
  expect(saved.images).toHaveLength(0); expect(saved.keyframeReels[0].useSoundtrack).toBe(false);
  expect(saved.keyframeReels[0].keyframes.frames[0].notes).toBe('Keep the visible blue material.');
  expect((await library(request,id)).reels[0].keyframes ?? null).toBe(source.keyframes ?? null);
  await page.reload(); await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready','true');
  await expect(page.locator('.workspace-right')).toBeVisible();
  await expect(tools.locator('.shot-reference-counts')).toContainText('Images 1/9');
    await tools.getByRole('button', { name: 'Prompt', exact: true }).click();
  await page.locator('.reel-setup-dialog').getByRole('button',{name:'Reel assistance',exact:true}).click();
  const assist=page.getByRole('dialog',{name:'Reel assistance',exact:true});
  await assist.locator('.model-chip').click();
  await page.getByRole('combobox',{name:'Text model',exact:true}).selectOption({label:'OpenRouter · Alternate mock model'});
  await page.getByRole('button',{name:'Set as project default',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Text model',exact:true})).not.toBeVisible();
  await assist.getByRole('button',{name:'Compose pair',exact:true}).click();
  await expect(assist).not.toBeVisible();
  await expect(page.locator('.reel-setup-dialog').getByRole('textbox',{name:'H3 prompt',exact:true})).toContainText('<Picture 1>',{timeout:25000});
  const compositions=(await (await request.get('/fixtures/reel-compositions')).json()).filter(c => c.context.request?.projectId===id || c.context.environment?.assetId===owner.id);
  expect(compositions).toHaveLength(1); expect(compositions[0].images).toHaveLength(1);
    await page.locator('.reel-setup-dialog').getByRole('button', { name: 'Done', exact: true }).click();
  await tools.getByRole('button',{name:'Generate reel',exact:true}).click();
  await expect.poll(async()=>(await library(request,id)).reels.length,{timeout:45000}).toBe(2);
  const generated=(await library(request,id)).reels.find(r=>r.id!==source.id);
  const captured=await (await request.get(`/fixtures/ai-jobs/${generated.generation.jobId}/video-inputs`)).json();
  expect(captured.inputs.map(i=>i.kind)).toEqual(['Image']);
  expect(JSON.stringify(captured.graph)).not.toMatch(/LoadVideo|VideoCondition|LoadAudio/);
  expect((await library(request,id)).assets[0].images).toHaveLength(owner.images.length);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('a trashed reel picture can be restored from reel references', async ({ page, request }) => {
  test.setTimeout(90000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`); await request.post(`/fixtures/${id}/prop-reel-owner`);
  const owner = (await library(request, id)).assets[0], picture = owner.images[0];
  await page.setViewportSize({ width: 1173, height: 1000 });
  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect(async () => { if (!await page.locator('.workspace-right').isVisible()) await page.locator('[data-toggle-pane=right]').click({ timeout: 1000 }); }).toPass({ timeout: 10000 });
  const editor = page.locator('.reel-tools'), references = page.locator('.reel-pictures-dialog');
  await editor.getByRole('button', { name: 'Manage references' }).click();
  await references.locator(`[data-reference="${owner.id}/${picture.id}"]`).click();
  await references.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await library(request, id)).reelDrafts[0]?.images.length).toBe(1);

  expect((await request.post(`/fixtures/${id}/trash/${picture.id}`)).ok()).toBe(true);
  await page.reload();
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect(async () => { if (!await page.locator('.workspace-right').isVisible()) await page.locator('[data-toggle-pane=right]').click({ timeout: 1000 }); }).toPass({ timeout: 10000 });
  await editor.getByRole('button', { name: 'Manage references' }).click();
  await expect(references.locator('.reference-issue')).toContainText('Restore or replace the unavailable reference.');
  await expect(references.locator('.reference-trash-restore')).toContainText('In Trash · 30 days remaining');
  await references.locator('.reference-trash-restore').screenshot({ path: 'artifacts/reel-picture-restore.png' });
  await references.locator('.reference-selection').screenshot({ path: 'artifacts/reel-picture-restore-row.png' });
  await references.getByRole('button', { name: 'Restore image', exact: true }).click();
  await expect(references.locator('.reference-issue')).toHaveCount(0);
  await expect(references.locator('.reference-trash-restore')).toHaveCount(0);
  await expect(references.locator('[aria-label="Picture 1: Crop image"]')).toBeEnabled();
  const restored = await library(request, id);
  expect(restored.assets[0].images.map(i => i.id)).toContain(picture.id); expect(restored.trash).toHaveLength(0);
  await references.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(references).not.toBeVisible();
  expect((await library(request, id)).reelDrafts[0].images[0].mediaId).toBe(picture.id);
});
