import { scriptAssist, closeComposer } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';
import { toolsTab } from './workspace-tools.js';

async function projectWithActs(page, request) {
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/revision-script`);
  await page.goto(`/projects/${project.id}/script`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  return { id: project.id, state: async () => (await (await request.get(`/fixtures/${project.id}`)).json()) };
}

test('folded acts select stable targets, revisions highlight actual changes, and undo preserves the script', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 950 });
  const { state } = await projectWithActs(page, request);
  const before = (await state()).script.blocks;
  await page.getByRole('button', { name: 'Collapse all', exact: true }).click();
  await expect(page.locator('.outline-title')).toHaveCount(3);
  await page.locator('.outline-title[title="ACT 3"]').click();
  await scriptAssist(page);
  await expect(page.locator('#script-scope')).toHaveValue('Act');
  await expect(page.locator('.assistant-target').first()).toHaveText('ACT 3');
  const pane = page.locator('.workspace-center .workspace-pane-body');
  await expect.poll(() => pane.evaluate(el => el.scrollTop)).toBeGreaterThan(800);
  expect(await page.evaluate(() => scrollY)).toBe(0);
  await closeComposer(page);
  await page.locator('.script-canvas [data-kind=Action]').first().click();
  await scriptAssist(page);
  await page.getByLabel('Instructions', { exact: true }).fill('Make the last act warmer.');
  await expect(page.locator('.assistant-target').first()).toHaveText('ACT 3');
  await page.getByRole('button', { name: 'Revise', exact: true }).click();
  const review = page.locator('.script-review-dialog');
  await expect(review.locator('.is-comparison')).toBeVisible();
  await expect(review.locator('ins').first()).toBeVisible();
  expect((await state()).history.runs.at(-1).target.originalBlocks[0].spans[0].text).toBe('ACT 3');
  await review.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(review).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Hide highlights', exact: true })).toBeVisible();
  await expect(page.locator('.script-applied-change').first()).toBeVisible();
  const after = (await state()).script.blocks, third = before.findIndex(b => b.kind === 'Act' && b.spans[0].text === 'ACT 3');
  expect(after.slice(0, third)).toEqual(before.slice(0, third));
  expect(after[third].id).toBe(before[third].id);
  expect(JSON.stringify(after)).not.toContain('script-applied-change');
  expect((await state()).approved).toBeNull();
  await expect(page.getByRole('button', { name: 'Hide highlights', exact: true })).toBeVisible();
  await expect(page.locator('.script-applied-change').first()).toBeVisible();
  await page.screenshot({ path: 'test-results/script-revision-highlights.png' });
  await toolsTab(page, 'Requests');
  await page.locator('.assistant-run').first().getByRole('button', { name: 'View changes', exact: true }).click();
  await expect(review).toContainText('Historical comparison');
  await review.getByText('Raw response', { exact: true }).click();
  await expect(review.locator('.raw-response')).toBeVisible();
  await expect(review.getByRole('button', { name: 'Apply changes', exact: true })).toHaveCount(0);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.locator('.script-applied-change')).toHaveCount(0);
  await expect.poll(async () => JSON.stringify((await state()).script.blocks)).toBe(JSON.stringify(before));
  await page.getByRole('button', { name: 'Expand ACT 3', exact: true }).click();
  await expect(page.locator('.outline-title')).toHaveCount(5);
  await page.getByRole('button', { name: 'Expand all', exact: true }).click();
  await expect(page.locator('.outline-title')).toHaveCount(9);
  const actMenu = page.locator('.script-outline-item').filter({ has: page.locator('.outline-title[title="ACT 3"]') });
  await actMenu.locator('summary').click(); await actMenu.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByRole('button', { name: /Delete act/ }).click();
  await scriptAssist(page);
  await expect(page.locator('.assistant-target').first()).toContainText('deleted');
  await expect(page.getByRole('button', { name: 'Revise', exact: true })).toBeDisabled();
});

test('request history stays bounded and historical retarget comparisons cannot be reapplied', async ({ page, request }) => {
  const { id, state } = await projectWithActs(page, request);
  await request.post(`/fixtures/${id}/request-history`); await page.reload();
  await toolsTab(page, 'Requests');
  await expect(page.locator('.assistant-run')).toHaveCount(20);
  await page.locator('.assistant-run').first().getByRole('button', { name: 'View changes', exact: true }).click();
  const review = page.locator('.script-review-dialog');
  await expect(review).toContainText('Before retargeted application');
  await expect(review).toContainText('Applied text 0');
  await expect(review.getByRole('button', { name: 'Review against current target' })).toHaveCount(0);
  await expect(review.getByRole('button', { name: 'Apply changes' })).toHaveCount(0);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Requests');
  await page.locator('.assistant-run').nth(1).getByRole('button', { name: 'Open response' }).click();
  await expect(review).toContainText('Malformed response for inspection');
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Requests');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.locator('.assistant-run')).toHaveCount(4);
  await page.locator('.assistant-run').last().getByRole('button', { name: 'Reuse instructions' }).click();
  await expect(page.getByLabel('Instructions', { exact: true })).toHaveValue('Request 23');
  await closeComposer(page);
  await expect(page.locator('.script-assistant .request-action-button')).toHaveText(/Revise/);
  await expect(page.locator('.assistant-latest')).toHaveCount(0);
  expect((await state()).history.runs).toHaveLength(24);
});

test('whole-script replacement is explicit and passage highlights stay within the selected text', async ({ page, request }) => {
  const { state } = await projectWithActs(page, request);
  const action = page.locator('.script-canvas [data-kind=Action]').first();
  const actionId = await action.getAttribute('data-block-id');
  const original = await action.innerText();
  await action.evaluate(node => {
    const text = document.createTreeWalker(node, NodeFilter.SHOW_TEXT).nextNode();
    const range = document.createRange(); range.setStart(text, 0); range.setEnd(text, 6);
    const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
  });
  await scriptAssist(page);
  await page.getByLabel('Work on').selectOption('Passage');
  await expect(page.locator('.assistant-target').first()).toContainText('Action');
  await page.getByRole('combobox', { name: 'Action', exact: true }).selectOption('Continue');
  await expect(page.getByRole('button', { name: 'Continue', exact: true })).toBeDisabled();
  await page.getByRole('combobox', { name: 'Action', exact: true }).selectOption('Revise');
  await scriptAssist(page);
  await page.getByLabel('Instructions', { exact: true }).fill('Make this more polite.');
  await page.getByRole('button', { name: 'Revise', exact: true }).click();
  const review = page.locator('.script-review-dialog');
  await expect(review.getByRole('region', { name: 'Original script', exact: true })).toContainText('Action');
  await expect(review.getByRole('region', { name: 'Original script', exact: true })).toContainText('window');
  await review.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(action).toHaveText('A tiny mouse politely bows' + original.slice(6));
  await expect(action.locator('.script-applied-change')).toHaveText(' tiny mouse politely bows');
  const stored = (await state()).script.blocks.find(b => b.id === actionId);
  expect(stored.spans.map(s => s.text).join('')).toBe('A tiny mouse politely bows' + original.slice(6));
  await page.getByRole('button', { name: 'Hide highlights', exact: true }).click();
  await expect(page.locator('.script-applied-change')).toHaveCount(0);
  await expect(page.locator('#script-operation option[value=Draft]')).toHaveCount(0);
  await scriptAssist(page);
  await page.getByText('Start over…', { exact: true }).click();
  await page.getByRole('button', { name: 'Draft replacement', exact: true }).click();
  await page.getByRole('button', { name: 'Draft script', exact: true }).click();
  await expect(review).toBeVisible();
  await expect(review.getByRole('button', { name: 'Replace entire script', exact: true })).toBeEnabled();
  await expect(review.locator('.is-comparison')).toHaveCount(0);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(page.locator('.script-canvas [data-kind=Act]')).toHaveCount(3);
  await page.setViewportSize({ width: 390, height: 844 });
  await scriptAssist(page);
  await page.getByRole('button', { name: /^(Review changes|View response|Needs attention)$/ }).click();
  await expect(review.getByRole('button', { name: 'Replace entire script', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/script-replacement-mobile.png' });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: /^(Review changes|View response|Needs attention)$/ })).toBeFocused();
});

