import { cropReference, shotAction, generateTakes, composeProduction, closeShotSetup, openShotSetup, editShotReference, toolsTab, assetView, imageAction, compositionState } from './workspace-tools.js';
import { planningComposer, submitPlanning, openPlanning } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';

async function setup(page, request) {
  const project = await (await request.get('/fixtures/new')).json();
  const assets = await (await request.post(`/fixtures/${project.id}/images`)).json();
  await request.post(`/fixtures/${project.id}/approved`);
  await page.goto(`/projects/${project.id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const plan = page.locator('.shot-planning-dialog');
  await expect(planningComposer(page)).toBeVisible();
  await expect(planningComposer(page)).toContainText(/15[.,]083/);
  await expect(planningComposer(page).getByRole('button', { name: 'Draft shots', exact: true })).toBeEnabled();
  await submitPlanning(page);
  await expect(plan.getByRole('button', { name: 'Add reviewed shots' })).toBeEnabled();
  await expect(plan).toContainText('You called?');
  await plan.getByRole('button', { name: 'Add reviewed shots' }).click();
  await expect(page.getByLabel('Action and camera')).toBeVisible();
  await expect.poll(async () => (await (await request.get(`/fixtures/${project.id}/shots`)).json()).shots.length).toBe(1);
  return { project, assets, state: () => compositionState(request, project.id) };
}

test('approved script to reviewed shots, background takes, independent continuity frame and Trash', async ({ page, request }) => {
  test.setTimeout(100000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { project, state } = await setup(page, request);
  await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  await page.locator('.project-image-picker .picker-grid button').first().click();
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await editShotReference(page);
  const crop = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Manage references' }) });
  await cropReference(page, crop);
  await crop.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await state()).shots[0].images[0]?.crop?.width).toBe(.5);
  await toolsTab(page, 'Generate');
  await toolsTab(page, 'Generate');
  await page.getByRole('combobox', { name: 'Default takes', exact: true }).selectOption('2');
  await composeProduction(page);
  await generateTakes(page);
  await expect.poll(async () => (await (await request.get(`/fixtures/${project.id}/video-runs`)).json()).length).toBeGreaterThan(0);
  const review = page.locator('.shot-review-dialog');
  await expect(review).toBeVisible({ timeout: 20000 });
  await expect(review.locator('video')).toHaveAttribute('preload', 'metadata');
  expect(await review.locator('video').evaluate(v => v.paused)).toBe(true);
  await review.locator('video').evaluate(v => v.play());
  await expect.poll(() => review.locator('video').evaluate(v => v.currentTime)).toBeGreaterThan(0);
  await review.locator('video').evaluate(v => v.pause());
  await expect(review.locator('.shot-candidate')).toHaveCount(2);
  await review.getByRole('button', { name: 'One more take' }).click();
  await expect(review.locator('.shot-candidate')).toHaveCount(3);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('link', { name: 'Assets', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(3);
  await page.getByRole('link', { name: 'Shots', exact: true }).click();
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Review latest batch' }).click();
  const position = review.getByRole('slider', { name: 'Video position' });
  await position.focus(); await page.keyboard.press('End');
  await expect(position).toHaveValue('38');
  await page.keyboard.press('ArrowLeft');
  await expect(position).toHaveValue('37');
  await expect(review.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeEnabled();
  await review.getByRole('button', { name: 'Save frame to Assets', exact: true }).click();
  const destination = review.locator('.image-copy-panel');
  await destination.getByLabel('New asset name').fill('Arrival state');
  await destination.getByLabel('Image name', { exact: true }).fill('Mouse after arrival');
  await destination.getByLabel('What to keep consistent (optional)').fill('Keep the hand position');
  await destination.getByRole('button', { name: 'Save', exact: true }).click();
  const assetState = async () => (await (await request.get(`/fixtures/${project.id}`)).json()).assets;
  await expect.poll(async () => (await assetState()).assets.flatMap(a => a.images).filter(i => i.source?.frame).length).toBe(1);
  const frame = (await assetState()).assets.flatMap(a => a.images).find(i => i.source?.frame);
  expect(frame.name).toBe('Mouse after arrival');
  expect(frame.preservationGuidance).toBe('Keep the hand position');
  expect((await assetState()).assets.find(a => a.images.some(i => i.id === frame.id)).name).toBe('Arrival state');
  expect(frame.source.frame.frameIndex).toBe(37); expect(frame.source.frame.timestamp).toBeCloseTo(37 / 24);
  await page.screenshot({ path: 'test-results/shots-frame-desktop.png' });
  const source = (await state()).shots[0].images[0];
  await request.post(`/fixtures/${project.id}/trash/${source.mediaId}`);
  await review.locator('.shot-input-preview summary').click();
  await review.getByRole('button', { name: 'Refresh references', exact: true }).click();
  await review.getByRole('button', { name: 'Show submitted crop', exact: true }).click();
  await expect(review).toContainText('In Trash');
  await review.getByRole('button', { name: 'Restore reference', exact: true }).click();
  await expect(review.getByRole('button', { name: 'Show full image', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(review.getByRole('slider', { name: 'Video position' })).toHaveValue('37');
  await review.locator('.shot-candidate').first().getByRole('button', { name: 'Discard', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length).toBe(2);
  await review.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length).toBe(3);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await shotAction(page, 'Duplicate');
  await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  await page.locator('.manual-reference-dialog').getByRole('combobox', { name: 'Reference type', exact: true }).selectOption('Images');
  await page.getByLabel('Origin', { exact: true }).selectOption('VideoFrame');
  await page.locator('.project-image-picker .picker-grid').getByRole('button', { name: /Mouse after arrival/ }).click();
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await composeProduction(page);
  await generateTakes(page);
  await expect(review).toBeVisible({ timeout: 20000 });
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(4);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  const runs = await (await request.get(`/fixtures/${project.id}/video-runs`)).json();
  const continuityRun = runs.find(run => run.snapshot.shot.title.endsWith('(copy)'));
  expect(continuityRun.snapshot.shot.images[0].mediaId).toBe(frame.id);
  await expect(review).not.toBeVisible();
  await page.screenshot({ path: 'test-results/shots-studio-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Review latest batch' }).click();
  await expect(review).toBeVisible();
  await review.locator('.shot-candidate').first().getByRole('button', { name: 'Discard', exact: true }).click();
  await page.screenshot({ path: 'test-results/shots-review-mobile.png' });
  await page.keyboard.press('Escape');
  await expect(review).not.toBeVisible();
  await page.goto('/trash');
  await expect(page.locator('.trash-toolbar')).toHaveAttribute('data-interactive', 'true');
  await page.locator('.trash-toolbar select').selectOption(project.id);
  await expect(page.locator('.trash-card')).toHaveCount(1);
  await page.locator('.trash-thumbnail').click();
  await expect(page.locator('.trash-preview video')).toBeVisible();
  await page.locator('.trash-preview').getByRole('button', { name: 'Close', exact: true }).focus();
  await page.keyboard.press('Escape');
  await expect(page.locator('.trash-preview')).not.toBeVisible();
  await page.locator('.trash-card').getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(page.locator('.trash-card')).toHaveCount(0);
});

for (const workflow of ['Krea2', 'Flux2Klein9bKv']) {
  test(`${workflow}: paused frame saves and crops into ordinary Assets for editing`, async ({ page, request }) => {
    test.setTimeout(90000);
    const { project, assets, state } = await setup(page, request);
    const library = async () => (await (await request.get(`/fixtures/${project.id}`)).json()).assets;
    await composeProduction(page);
  await generateTakes(page);
    const review = page.locator('.shot-review-dialog');
    await expect(review).toBeVisible({ timeout: 20000 });
    const position = review.getByRole('slider', { name: 'Video position' });
    await position.focus(); await page.keyboard.press('End');
    await expect(review.locator('.take-player')).toHaveAttribute('data-frame-index', '38');
    await expect(review.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeEnabled();
    await review.getByRole('button', { name: 'Save frame to Assets', exact: true }).click();
    const destination = review.locator('.image-copy-panel');
    await destination.getByLabel('New asset name').fill('Arrival state');
    await destination.getByLabel('Image name', { exact: true }).fill('Mouse paused at doorway');
    await destination.getByRole('button', { name: 'Save and edit', exact: true }).click();
    await expect(page).toHaveURL(/assets\?assetId=.*&imageId=.*&edit=true/);
    await expect(page.getByLabel('Edit instruction')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Continuity frames', exact: true })).toHaveCount(0);
    const frameAsset = (await library()).assets.find(a => a.name === 'Arrival state');
    const frame = frameAsset.images[0];
    expect(frame.source.frame.frameIndex).toBe(38); expect(frame.isReference).toBe(false);
    const beforeTake = (await state()).takes[0];
    await page.getByRole('button', { name: 'Image actions', exact: true }).first().click();
    await page.getByRole('menuitem', { name: 'Move to asset…', exact: true }).click();
    const move = page.locator('.image-move-dialog');
    await move.getByLabel('Destination asset').selectOption(assets.assets[0].id);
    await move.getByRole('button', { name: 'Move and edit', exact: true }).click();
    await expect(move).not.toBeVisible();
    await expect(page.getByLabel('Edit instruction')).toBeFocused();
    expect((await library()).assets[0].images.find(i => i.id === frame.id).source).toEqual(frame.source);
    // The original Save-and-edit URL still locates this exact frame after its move.
    await page.reload(); await expect(page.getByLabel('Edit instruction')).toBeVisible();
    await expect(page.locator('.asset-list-row.selected .asset-choice')).toContainText(assets.assets[0].name);
    const frameCard = page.locator('.reference-card').filter({ has: page.locator(`img[src$="/${frame.id}"]`) });
    await frameCard.getByRole('button', { name: 'Image actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Crop image', exact: true }).click();
    const crop = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Crop image', exact: true }) });
    await crop.getByLabel('Crop shape').selectOption('1:1');
    await crop.getByLabel('Destination asset').selectOption(assets.assets[0].id);
    await crop.getByLabel('Image name', { exact: true }).fill('Mouse face crop');
    await crop.getByRole('button', { name: 'Save and edit', exact: true }).click();
    await expect(crop).not.toBeVisible();
    await expect(page.getByLabel('Edit instruction')).toBeVisible();
    const copied = (await library()).assets[0].images.find(i => i.source?.crop);
    expect(copied.width).toBe(copied.height); expect(copied.source.crop.imageId).toBe(frame.id);
    await toolsTab(page, 'Prompt');
    await page.getByLabel('Image workflow', { exact: true }).selectOption(workflow);
    await toolsTab(page, 'Prompt');
    await page.getByLabel('Edit instruction').fill('Keep her pose and make the lighting warmer.');
    await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
    const images = page.locator('.image-review-dialog');
    await expect(images).toBeVisible({ timeout: 20000 });
    await images.getByRole('button', { name: 'Close', exact: true }).click();
    await expect.poll(async () => (await library()).assets[0].images.filter(i => i.generation?.edit?.sourceImageId === copied.id).length).toBe(1);
    expect((await state()).takes[0]).toEqual(beforeTake);
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    await page.screenshot({ path: `test-results/frame-assets-${workflow}-mobile.png`, fullPage: true });
    await page.getByRole('link', { name: 'Shots', exact: true }).click();
    await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
    await page.locator('.manual-reference-dialog').getByRole('combobox', { name: 'Reference type', exact: true }).selectOption('Images');
    await page.getByLabel('Origin', { exact: true }).selectOption('Cropped');
    await page.locator('.project-image-picker .picker-grid').getByRole('button', { name: /Mouse face crop/ }).click();
    await page.locator('.manual-reference-dialog').getByRole('tab', { name: /^Selected references/ }).click();
    await page.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
    await page.getByRole('button', { name: 'Apply changes', exact: true }).click();
    await expect.poll(async () => (await state()).shots[0].images[0]?.mediaId).toBe(copied.id);
  });
}

test('the take player ignores stale frames, retries missing archives and follows displayed playback', async ({ page, request }) => {
  test.setTimeout(65000);
  const { project, state } = await setup(page, request);
  await toolsTab(page, 'Generate');
  await page.getByLabel('Save lossless frames', { exact: true }).check();
  await page.getByRole('combobox', { name: 'Default takes', exact: true }).selectOption('2');
  await composeProduction(page);
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog'), player = review.locator('.take-player');
  await expect(review).toBeVisible({ timeout: 20000 });
  await expect.poll(async () => (await state()).takes.length).toBe(2);
  const firstTake = (await state()).takes[0];
  let missing = true;
  await page.route(`**/takes/${firstTake.id}/frames/30`, async route => {
    if (missing) await route.fulfill({ status: 404 }); else await route.continue();
  });
  await page.route(`**/takes/${firstTake.id}/frames/20`, async route => {
    await new Promise(resolve => setTimeout(resolve, 600)); await route.continue().catch(() => {});
  });
  const position = review.getByRole('slider', { name: 'Video position' });
  async function seek(index) {
    await position.evaluate((el, value) => { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); }, String(index));
  }
  await seek(20); await seek(38);
  await expect(player).toHaveAttribute('data-frame-index', '38');
  await expect(player.locator('.take-paused-frame')).toBeVisible();
  await seek(30);
  await expect(player.getByRole('alert')).toContainText('unavailable');
  await expect(player.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeDisabled();
  missing = false; await player.getByRole('button', { name: 'Retry frame', exact: true }).click();
  await expect(player).toHaveAttribute('data-frame-index', '30');
  await expect(player.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeEnabled();
  await seek(20);
  await review.getByRole('button', { name: 'Take 2', exact: true }).click();
  await expect(player).toHaveAttribute('data-frame-index', '0');
  await expect(player.locator('video')).toHaveAttribute('src', new RegExp((await state()).takes[1].id));
  await position.focus(); await page.keyboard.press('Home');
  await player.locator('video').evaluate(video => {
    window.presentedTime = 0;
    function track(_, frame) { window.presentedTime = frame.mediaTime; video.requestVideoFrameCallback(track); }
    video.requestVideoFrameCallback(track);
  });
  await player.getByRole('button', { name: 'Play', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.presentedTime)).toBeGreaterThan(.1);
  await player.getByRole('button', { name: 'Save frame to Assets', exact: true }).click();
  await expect(review.locator('.image-copy-panel')).toBeVisible();
  const presented = await page.evaluate(() => window.presentedTime);
  await expect(player).toHaveAttribute('data-frame-index', String(Math.floor(presented * 24 + .0001)));
  await review.locator('.image-copy-panel').getByRole('button', { name: 'Cancel', exact: true }).click();
  await player.getByRole('button', { name: 'Fullscreen', exact: true }).click();
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true);
  await page.evaluate(() => document.exitFullscreen());
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(review).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Review latest batch' })).toBeFocused();
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Review latest batch' }).click();
  await expect(review).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(review).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Review latest batch' })).toBeFocused();
});

test('paused seeking without presented-frame callbacks requires the archived frame before saving', async ({ page, request }) => {
  await page.addInitScript(() => { HTMLVideoElement.prototype.requestVideoFrameCallback = undefined; });
  const { state } = await setup(page, request);
  await toolsTab(page, 'Generate');
  await page.getByLabel('Save lossless frames', { exact: true }).check();
  await composeProduction(page);
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog'), player = review.locator('.take-player');
  await expect(review).toBeVisible({ timeout: 20000 });
  await player.getByRole('slider', { name: 'Video position' }).focus(); await page.keyboard.press('End');
  await expect(player).toHaveAttribute('data-frame-index', String((await state()).takes[0].frames.length - 1));
  await expect(player.locator('.take-paused-frame')).toBeVisible();
  await player.getByRole('button', { name: 'Save frame to Assets', exact: true }).click();
  await expect(review.getByLabel('Destination asset')).toBeFocused();
  await review.locator('.image-copy-panel').getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(player.getByRole('button', { name: 'Save frame to Assets', exact: true })).toBeFocused();
});

test('a shot on retired 8-step Turbo survives reload and one more take preserves its captured sampling', async ({ page, request }) => {
  test.setTimeout(80000);
  const { project, state } = await setup(page, request);
  const quality = page.getByRole('combobox', { name: 'Generation preset', exact: true });
  await toolsTab(page, 'Generate');
  await page.getByLabel('Save lossless frames', { exact: true }).check();
  await expect.poll(async () => (await state()).shots[0].saveLosslessFrames).toBe(true);
  // Turbo 8 is retired, so it is no longer offered; a shot saved with it keeps it.
  await expect(quality.locator('option[value=turbo8]')).toHaveCount(0);
  await request.post(`/fixtures/${project.id}/shot-preset?key=turbo8`);
  await page.reload();
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate');
  await expect(quality).toHaveValue('turbo8');
  await expect(quality.locator('option:checked')).toHaveText('Turbo · 8 steps · Retired');
  await expect(page.locator('.shot-generation')).toContainText('Euler · video shift 12 · audio shift 3');
  await expect.poll(async () => (await state()).shots[0].turboSteps).toBe(8);
  await page.reload();
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await toolsTab(page, 'Generate');
  await expect(quality).toHaveValue('turbo8');
  await composeProduction(page);
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog');
  await expect(review).toBeVisible({ timeout: 20000 });
  await review.getByText('Generation details', { exact: true }).click();
  await expect(review).toContainText('Turbo · 8 steps');
  const first = (await state()).takes[0].snapshot;
  expect(first.sampling).toMatchObject({ steps: 8, sampler: 'euler', scheduler: 'simple', videoShift: 12, audioShift: 3, loraStrength: 1 });
  expect(first.sampling.lora).toContain('8step');
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await toolsTab(page, 'Generate');
  await quality.selectOption('standard');
  await expect.poll(async () => (await state()).shots[0].turbo).toBe(false);
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Review latest batch' }).click();
  await review.getByRole('button', { name: 'One more take', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 30000 }).toBe(2);
  expect((await state()).takes[1].snapshot.sampling).toEqual(first.sampling);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await toolsTab(page, 'Generate');
  // Once the shot moves off the retired preset, it is no longer offered.
  await expect(quality.locator('option[value=turbo8]')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/shots-turbo8-mobile.png', fullPage: true });
});

test('a crashed video batch cancels locally and releases generation controls', async ({ page, request }) => {
  const { project } = await setup(page, request);
  await page.getByLabel('Action and camera').fill('MOCK_COMFY_CRASH A continuous camera move.');
  await page.getByLabel('Action and camera').blur();
  await toolsTab(page, 'Generate');
  await page.getByRole('combobox', { name: 'Default takes', exact: true }).selectOption('2');
  await composeProduction(page);
  await generateTakes(page);
  const banner = page.locator('.shot-job-banner');
  await expect(banner).toContainText('ComfyUI connection failed.');
  // The batch stopped without saving a take, so there is nothing to view or cancel; it can be dismissed.
  await expect(banner.getByRole('button', { name: 'View batch', exact: true })).toHaveCount(0);
  await expect(banner.getByRole('button', { name: 'Cancel generation', exact: true })).toHaveCount(0);
  await banner.getByRole('button', { name: 'Dismiss this batch', exact: true }).click();
  await expect(banner).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Review latest batch' }).click();
  const review = page.locator('.shot-review-dialog');
  await expect(review).toContainText('Cancelled. Completed takes are retained.');
  const runs = await (await request.get(`/fixtures/${project.id}/video-runs`)).json();
  expect(runs[0].cancelRequested).toBe(true);
  expect(runs[0].candidates.map(c => c.state)).toEqual([6, 6]); // VideoCandidateState.Cancelled in the fixture API.
  const jobs = await (await request.get('/fixtures/ai-jobs')).json();
  await review.getByRole('button', { name: 'Recover completed takes', exact: true }).click();
  await expect(review.getByRole('button', { name: 'Recover completed takes', exact: true })).toBeEnabled();
  await expect(review).toContainText('Cancelled. Completed takes are retained.');
  expect((await (await request.get('/fixtures/ai-jobs')).json()).map(j => j.id)).toEqual(jobs.map(j => j.id));
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await expect(banner).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
});

test('manual shots require duration and planning cancellation cannot apply', async ({ page, request }) => {
  const { project } = await setup(page, request);
  await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect(page.getByLabel('Shot title', { exact: true })).toHaveValue('Untitled shot');
  await page.getByLabel('Action and camera').fill('A quiet continuous camera move.');
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeDisabled();
  await page.getByLabel('Duration (seconds)', { exact: true }).fill('15');
  await page.getByLabel('Duration (seconds)', { exact: true }).blur();
  await expect(page.locator('body')).toContainText(/15[.,]083 s/);
  await composeProduction(page);
  await closeShotSetup(page);
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeEnabled();
  await openPlanning(page);
  const plan = page.locator('.shot-planning-dialog');
  await planningComposer(page).getByLabel('Directing instructions (optional)').fill('SLOW');
  await submitPlanning(page);
  await plan.getByRole('button', { name: 'Cancel request' }).click();
  await expect(plan.getByRole('button', { name: 'Add reviewed shots' })).toBeDisabled();
  await expect(plan).toContainText('cancelled');
  await page.keyboard.press('Escape');
  await expect.poll(async () => (await (await request.get(`/fixtures/${project.id}/shots`)).json()).shots.length).toBe(2);
  await page.reload();
  await expect(page.locator('.shot-list-row')).toHaveCount(2);
});


test('character voice upload, excerpt selection and shot assignment', async ({ page, request }) => {
  test.setTimeout(90000);
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/images`);
  await request.post(`/fixtures/${project.id}/approved`);
  await request.post(`/fixtures/${project.id}/production-shot`);
  const state = () => compositionState(request, project.id);
  await page.goto(`/projects/${project.id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('.asset-list-row.selected')).toHaveCount(1);
  await assetView(page, 'Voices');
  const importVoice = async () => {
    if (!await page.getByRole('button', { name: 'Import voice', exact: true }).isVisible())
      await page.locator('.asset-import-menu > summary').click();
    await page.getByRole('button', { name: 'Import voice', exact: true }).click();
  };
  await importVoice();
  const voices = page.locator('.voice-dialog');
  const data = Buffer.alloc(44 + 128000);
  data.write('RIFF'); data.writeUInt32LE(data.length - 8, 4); data.write('WAVEfmt ', 8); data.writeUInt32LE(16, 16);
  data.writeUInt16LE(1, 20); data.writeUInt16LE(1, 22); data.writeUInt32LE(32000, 24); data.writeUInt32LE(64000, 28);
  data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34); data.write('data', 36); data.writeUInt32LE(128000, 40);
  await expect.poll(() => voices.locator('input[type=file]').evaluate(el => typeof el._blazorInputFileNextFileId === 'number')).toBe(true);
  await voices.locator('input[type=file]').setInputFiles({ name: 'voice.wav', mimeType: 'audio/wav', buffer: data });
  await expect(voices.locator('audio')).toHaveCount(1);
  await expect(voices.getByLabel('Recording name')).toHaveValue('voice');
  expect((await (await request.get(`/fixtures/${project.id}`)).json()).assets.voices).toHaveLength(0);
  await voices.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(voices).not.toBeVisible();
  await importVoice();
  expect((await (await request.get(`/fixtures/${project.id}`)).json()).assets.voices).toHaveLength(0);
  await expect.poll(() => voices.locator('input[type=file]').evaluate(el => typeof el._blazorInputFileNextFileId === 'number')).toBe(true);
  await voices.locator('input[type=file]').setInputFiles({ name: 'voice.wav', mimeType: 'audio/wav', buffer: data });
  await expect(voices.getByLabel('Recording name')).toHaveValue('voice');
  await voices.getByLabel('Recording name').fill('Juniper warm voice');
  await voices.getByLabel('Start (seconds)', { exact: true }).fill('0.5');
  await voices.getByLabel('End (seconds)', { exact: true }).fill('1.5');
  await voices.getByRole('button', { name: 'Play excerpt', exact: true }).click();
  await expect.poll(() => voices.locator('audio').evaluate(el => el.currentTime)).toBeGreaterThan(0.5);
  await expect.poll(() => voices.locator('audio').evaluate(el => el.paused)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/voice-import-mobile.png' });
  await expect(voices.getByRole('button', { name: 'Save voice reference', exact: true })).toBeInViewport();
  await voices.getByRole('button', { name: 'Save voice reference', exact: true }).click();
  await expect(voices).not.toBeVisible();
  const voiceCard = page.locator('.asset-media-card').filter({ hasText: 'Juniper warm voice' });
  await expect(voiceCard).toHaveCount(1);
  const library = (await (await request.get(`/fixtures/${project.id}`)).json()).assets;
  expect(library.voices[0].excerptDuration).toBe(1);
  await voiceCard.getByRole('button', { name: 'Actions for Juniper warm voice', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click();
  await expect(voiceCard).toHaveCount(0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(voiceCard).toHaveCount(1);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole('link', { name: 'Shots', exact: true }).click();
  await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const refs = page.locator('.manual-reference-dialog');
  if (!await refs.getByLabel('Voice for Juniper', { exact: true }).count())
    await refs.getByLabel('Add character voice', { exact: true }).selectOption(library.voices[0].assetId);
  await refs.getByLabel('Voice for Juniper', { exact: true }).selectOption(`voice:${library.voices[0].id}`);
  await refs.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(refs).not.toBeVisible();
  await expect(page.locator('.shot-voice')).toHaveCount(1);
  await expect.poll(async () => (await state()).shots[0].voices.length).toBe(1);
  expect((await state()).shots[0].voices[0].speaker).toBe('JUNIPER');
  await composeProduction(page);
  await generateTakes(page);
  const jobs = async () => (await (await request.get('/fixtures/ai-jobs')).json()).find(j => j.target.projectId === project.id && j.kind === 'Video');
  await expect.poll(async () => (await jobs())?.state, { timeout: 45000 }).toBe('Completed');
  const capture = await (await request.get(`/fixtures/ai-jobs/${(await jobs()).id}/video-inputs`)).json();
  expect(capture.inputs.map(i => i.kind)).toEqual(['Audio']);
  expect(JSON.stringify(capture.graph)).not.toContain('ref_video_audios.ref_video_audio_');
});


test('shot autosave keeps rapid edits and conflicting tabs retain downloadable drafts', async ({ page, request, context }) => {
  const { project, state } = await setup(page, request);
  const other = await context.newPage();
  await other.goto(`/projects/${project.id}/shots`);
  await expect(other.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByLabel('Action and camera').fill('A slow camera move.');
  await page.getByLabel('Action and camera').pressSequentially(' The mouse waits.', { delay: 5 });
  await expect.poll(async () => (await state()).shots[0].description).toBe('A slow camera move. The mouse waits.');
  await other.getByLabel('Action and camera').fill('A different unsaved direction.');
  await expect(other.locator('body')).toContainText('Save failed · draft retained');
  await other.getByRole('link', { name: 'Assets', exact: true }).click();
  await expect(other).toHaveURL(new RegExp(`/projects/${(await (await request.get(`/fixtures/${project.id}/project-route`)).json()).slug}/shots$`));
  await expect(other.getByLabel('Action and camera')).toHaveValue('A different unsaved direction.');
  const download = other.waitForEvent('download');
  await other.getByRole('button', { name: 'Download unsaved copy' }).click();
  expect((await download).suggestedFilename()).toBe('unsaved-composition.json');
  await other.getByRole('button', { name: 'Reload saved version' }).click();
  await expect(other.getByLabel('Action and camera')).toHaveValue('A slow camera move. The mouse waits.');
  await other.close();
});

test('shared preservation defaults, local overrides and captured take guidance remain independent', async ({ page, request }) => {
  test.setTimeout(100000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { project, assets, state } = await setup(page, request);
  const person = assets.assets.find(a => a.name === 'Juniper');
  const library = async () => (await (await request.get(`/fixtures/${project.id}`)).json()).assets;
  async function openAssetDetails(target) {
    await target.goto(`/projects/${project.id}/assets?assetId=${person.id}`);
    await expect(target.locator('.asset-list-row.selected')).toHaveAttribute('data-asset-id', person.id);
    await assetView(target, 'Asset details');
    await expect(target.getByLabel('Asset name', { exact: true })).toHaveValue('Juniper');
  }
  await openAssetDetails(page);
  await page.getByLabel('Character identity', { exact: true }).fill('Preserve her face and dark hair.');
  await assetView(page, 'Images');
  await expect.poll(async () => (await library()).assets.find(a => a.id === person.id).preservationGuidance).toBe('Preserve her face and dark hair.');
  await imageAction(page, 'Edit details');
  const imageReview = page.locator('.image-review-dialog');
  await imageReview.locator('.media-details-disclosure').filter({ has: page.getByText('Use guidance', { exact: true }) }).locator('summary').click();
  await imageReview.getByLabel('Use guidance', { exact: true }).fill('Preserve the gray hoodie.');
  await imageReview.getByRole('button', { name: 'Save details', exact: true }).click();
  await imageReview.getByRole('button', { name: 'Close image review', exact: true }).click();
  await expect.poll(async () => (await library()).assets.find(a => a.id === person.id).images[0].preservationGuidance).toBe('Preserve the gray hoodie.');
  await page.getByRole('link', { name: 'Shots', exact: true }).click();
  await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const reference = page.locator('.manual-reference-dialog');
  await reference.locator(`[data-reference="${person.id}/${person.images[0].id}"]`).click();
  await reference.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
  await reference.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(reference).toBeHidden();
  await editShotReference(page);
  await expect(reference).toContainText('Preserve her face and dark hair.');
  await expect(reference).toContainText('Preserve the gray hoodie.');
  await reference.getByLabel('AI use hint', { exact: true }).selectOption('Identity');
  await reference.getByRole('button', { name: 'Customize for this setup', exact: true }).click();
  const override = reference.getByLabel('Composition preservation override', { exact: true });
  await expect(override).toBeFocused();
  await override.fill('Keep her identity; allow the outfit transformation.');
  await reference.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await state()).shots[0].images[0].preservationOverride).toContain('allow the outfit transformation');
  await editShotReference(page);
  await reference.getByRole('button', { name: 'Reset to shared defaults', exact: true }).click();
  await expect(reference.getByRole('button', { name: 'Customize for this setup', exact: true })).toBeFocused();
  await reference.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await state()).shots[0].images[0].preservationOverride ?? null).toBeNull();
  await toolsTab(page, 'Generate');
  await page.getByLabel('Save lossless frames', { exact: true }).check();
  await composeProduction(page);
  await generateTakes(page);
  const review = page.locator('.shot-review-dialog');
  await expect(review).toBeVisible({ timeout: 20000 });
  await expect(review).toContainText('WebP archive');
  await expect.poll(async () => (await state()).takes.length).toBe(1);
  const firstTake = (await state()).takes[0];
  expect(firstTake.frames).toHaveLength(39);
  expect(new Set(firstTake.frames.map(f => f.fileName)).size).toBe(2);
  expect(firstTake.frames.every(f => f.fileName.endsWith('.webp'))).toBe(true);
  expect(firstTake.frames[24].archiveFrameIndex).toBe(0);
  expect(firstTake.snapshot.referenceGuidance[0].effective).toContain('Preserve her face and dark hair.');
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  const other = await page.context().newPage();
  await openAssetDetails(other);
  await other.getByLabel('Character identity', { exact: true }).fill('Different defaults for future shots.');
  await assetView(other, 'Images');
  await expect.poll(async () => (await library()).assets.find(a => a.id === person.id).preservationGuidance).toBe('Different defaults for future shots.');
  await other.close();
  await page.locator('.shot-reference-details > summary').click();
  await page.getByRole('button', { name: 'Refresh Assets', exact: true }).click();
  await editShotReference(page);
  await expect(reference).toContainText('Different defaults for future shots.');
  await reference.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Review latest batch', exact: true }).click();
  await review.locator('.shot-input-preview summary').click();
  await expect(review.locator('.shot-input-preview')).toContainText('Preserve her face and dark hair.');
  await expect(review.locator('.shot-input-preview')).not.toContainText('Different defaults for future shots.');
  await review.getByRole('button', { name: 'One more take', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 20000 }).toBe(2);
  for (const take of (await state()).takes) {
    expect(take.snapshot.referenceGuidance).toEqual(firstTake.snapshot.referenceGuidance);
    expect(take.snapshot.prompt).toBe(firstTake.snapshot.prompt);
  }
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await toolsTab(page, 'References');
  await editShotReference(page);
  await reference.getByRole('button', { name: 'Customize for this setup', exact: true }).click();
  await expect(override).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/shot-reference-guidance-mobile.png' });
});
