import { test, expect } from './fixtures.js';
test.beforeEach(async ({ request }) => { await request.post('/fixtures/generation-setups/reset'); });
import { openShotSetup, closeShotSetup } from './workspace-tools.js';

for (const narrow of [false, true]) test(`named shot setup dialog saves edits and restores focus (${narrow ? 'phone' : 'desktop'})`, async ({ page, request }) => {
  page.setDefaultTimeout(15000);
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1272 });
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('[data-workspace-group=center]').getByRole('tab')).toHaveText(['Shot', 'Takes0']);
  await expect(page.locator('.shot-editor .setup-toolbar')).toHaveCount(0);
  const setups = async () => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions;
  const original = (await setups())[0];
  const dialog = page.locator('.shot-setup-dialog');
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await openShotSetup(page);
  await editor.fill('A handwritten prompt.');
  await expect(dialog.getByLabel('Named setup', { exact: true })).toBeHidden();
  await openShotSetup(page, 'Generation settings');
  await expect(editor).toBeHidden();
  // Duplication must flush even the most recent editor input.
  await dialog.getByText('Setup options', { exact: true }).click();
  await dialog.getByRole('button', { name: 'Duplicate setup', exact: true }).click();
  await expect.poll(async () => (await setups()).length).toBe(2);
  await expect(page.locator('#shot-setup-prompt-panel')).toHaveAttribute('data-setup-id', (await setups())[1].id);
  await dialog.getByLabel('Setup name', { exact: true }).fill(`Close-up · soft light ${narrow ? 'phone' : 'desktop'}`);
  await dialog.getByText('Setup options', { exact: true }).click();
  await openShotSetup(page);
  await expect(dialog.getByLabel('Named setup', { exact: true })).toBeHidden();
  await expect(editor).toHaveText('A handwritten prompt.');
  await editor.fill('The revised prompt belongs to the shot.');
  await openShotSetup(page, 'Generation settings');
  await dialog.getByLabel('Default resolution', { exact: true }).selectOption('detail');
  await dialog.getByLabel('Default takes', { exact: true }).selectOption('3');
  await closeShotSetup(page);
  await expect(page.getByRole('button', { name: 'Edit generation preset', exact: true })).toBeFocused();
  await expect.poll(async () => (await setups())[1].name).toBe(`Close-up · soft light ${narrow ? 'phone' : 'desktop'}`);
  expect((await setups())[1].inputs.resolution).toBe(2);
  expect((await setups())[1].takeCount).toBe(3);
  expect((await setups())[0].prompt).toBe('The revised prompt belongs to the shot.');
  await openShotSetup(page, 'Generation settings');
  await dialog.getByLabel('Named setup', { exact: true }).selectOption(original.generationSetupId);
  await expect(page.locator('#shot-setup-prompt-panel')).toHaveAttribute('data-setup-id', original.id);
  await expect(dialog.getByLabel('Default resolution', { exact: true })).toHaveValue('preview');
  await openShotSetup(page);
  await expect(editor).toHaveText('The revised prompt belongs to the shot.');
  await editor.press('Control+End'); await editor.pressSequentially(' Saved on Escape.');
  await editor.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Prompt', exact: true })).toBeFocused();
  await expect.poll(async () => (await setups())[0].prompt).toContain('Saved on Escape.');
  await page.goto(`/projects/${id}/shots?view=Prompt`);
  await expect(dialog).toBeVisible();
  await expect(editor).toContainText('Saved on Escape.');
  await page.screenshot({ path: `artifacts/shots-setup-prompt-${narrow ? 'phone' : 'desktop'}.png` });
  await openShotSetup(page, 'Generation settings');
  await expect(dialog.getByLabel('Default resolution', { exact: true })).toBeVisible();
  await page.screenshot({ path: `artifacts/shots-setup-settings-${narrow ? 'phone' : 'desktop'}.png` });
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await closeShotSetup(page);
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});
