import { cropReference, openShotSetup, closeShotSetup, toolsTab } from './workspace-tools.js';
import { test, expect } from './fixtures.js';
test.beforeEach(async ({ request }) => { await request.post('/fixtures/generation-setups/reset'); });
const setups = async (request, id) => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions;
const shotTab = (page, name) => page.locator('[data-workspace-group=center]').getByRole('tab', { name, exact: true });
async function shotAction(page, name) { await closeShotSetup(page); await page.locator('.shot-outline-item.selected').getByRole('button', { name: /^Actions for shot / }).click(); await page.getByRole('menuitem', { name, exact: true }).click(); }
const shots = async (request, id) => (await (await request.get(`/fixtures/${id}/shots`)).json());
async function fixture(page, request) {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`); await request.post(`/fixtures/${id}/images`); await request.post(`/fixtures/${id}/production-shot`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('.shot-setup-summary select.generation-preset-select option:checked')).toHaveText('Default setup');
  return id;
}
async function references(page) {
  await toolsTab(page, 'References');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const dialog = page.locator('.manual-reference-dialog');
  await dialog.locator('[data-reference]').first().click();
  await expect(dialog.getByLabel('Character', { exact: true })).toHaveCount(0);
  await dialog.getByLabel('AI use hint').selectOption('Setting');
  await cropReference(page, dialog);
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(dialog).not.toBeVisible();
}
async function promptAssist(page) { if (!await page.getByLabel('Direction for AI').isVisible()) await page.getByRole('button', { name: 'Prompt assistance', exact: true }).click(); await expect(page.getByLabel('Direction for AI')).toBeVisible(); }
async function chooseModel(page) {
  await promptAssist(page);
  await page.locator('.ai-assist-dialog .assist-composer-model .model-chip').click();
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption({ label: 'OpenRouter · Alternate mock model' });
  await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
  await promptAssist(page);
}
async function compose(page) {
  await openShotSetup(page);
  await chooseModel(page);
  await page.getByRole('button', { name: 'Compose prompt', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'H3 prompt', exact: true })).toContainText('Vision-composed staging');
  await expect(page.getByRole('button', { name: 'Apply changes', exact: true })).toHaveCount(0);
}
test('unified coverage, initial composition, manual edit, immutable batch and take selection', async ({ page, request }) => {
  test.setTimeout(120000);
  const id = await fixture(page, request);
  await expect(page.getByRole('link', { name: 'Production', exact: true })).toHaveCount(0);
  await expect(page.getByLabel('Shot title')).toBeVisible();
  expect((await setups(request, id))[0].prompt).toBe('');
  await references(page); await compose(page);
  let setup = (await setups(request, id))[0];
  expect(setup.inputs.images[0].aiUseHint).toBe('Setting');
  expect(setup.inputs.images[0].crop.width).toBe(.5);
  expect(setup.shot).toBeUndefined();
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await editor.press('Control+End'); await editor.press('Enter'); await editor.pressSequentially('A soft room tone.');
  await expect.poll(async () => (await setups(request, id))[0].prompt).toContain('A soft room tone.');
  setup = (await setups(request, id))[0];
  await closeShotSetup(page); await page.getByRole('button', { name: 'Generate takes', exact: true }).click();
  const review = page.locator('.shot-review-dialog');
  await expect(review).toBeVisible();
  await expect.poll(async () => (await shots(request, id)).takes.length).toBe(1);
  expect((await shots(request, id)).takes[0].snapshot.prompt).toBe(setup.prompt);
  await review.getByRole('button', { name: 'Use this take', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).shots[0].selectedTakeId).toBe((await shots(request, id)).takes[0].id);
  await review.getByRole('button', { name: 'One more take', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).takes.length).toBe(2);
  expect((await shots(request, id)).takes.every(t => t.snapshot.prompt === setup.prompt)).toBe(true);
  await review.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('[data-workspace-group=center]').getByRole('tab', { name: 'Takes', exact: true }).click();
  await expect(page.getByLabel('Action and camera')).toBeHidden();
  await expect(shotTab(page, 'Takes').locator('.tab-count')).toHaveText('2');
  await expect(page.locator('.unified-take-card')).toHaveCount(2);
  await expect(page.locator('.selected-take-badge')).toHaveText('Selected');
  await page.screenshot({ path: 'artifacts/unified-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/unified-narrow.png' });
});
test('literal document editing, exact view, clear and undo, revisions and shared shot direction', async ({ page, request }) => {
  test.setTimeout(120000);
  const id = await fixture(page, request); const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await openShotSetup(page);
  const literal = 'subject_definitions:\n<Picture 1> — Åsa 👋\n\n<d>[Swedish] Hej!\nAndra raden.</d>\n';
  await editor.evaluate((element, text) => { const data = new DataTransfer(); data.setData('text/plain', text); element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true })); }, literal);
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(literal);
  await page.getByLabel('Exact text', { exact: true }).check();
  expect((await setups(request, id))[0].prompt).toBe(literal);
  await page.reload(); await openShotSetup(page); await expect(editor).toContainText('Åsa 👋');
  await page.getByRole('button', { name: 'Clear prompt', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe('');
  await page.locator('.shot-setup-dialog').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(literal);
  await page.getByRole('button', { name: 'Clear prompt', exact: true }).click();
  await references(page); await compose(page);
  const initial = (await setups(request, id))[0].prompt;
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('Move the camera closer.');
  await promptAssist(page);
  await page.getByRole('button', { name: 'Revise with AI', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeVisible();
  expect((await setups(request, id))[0].prompt).toBe(initial);
  await page.reload(); await openShotSetup(page);
  await page.getByRole('button', { name: 'Review changes', exact: true }).click();
  await page.locator('.prompt-review-dialog').getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(editor).toContainText('Move the camera closer.');
  const revised = (await setups(request, id))[0].prompt;
  await closeShotSetup(page); await openShotSetup(page);
  await page.getByRole('button', { name: 'Undo prompt edit', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(initial);
  await page.getByRole('button', { name: 'Redo prompt edit', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(revised);
  await openShotSetup(page, 'Generation settings');
  await page.getByText('Setup options', { exact: true }).click();
  await page.getByRole('button', { name: 'Duplicate setup', exact: true }).click();
  await expect.poll(async () => (await setups(request, id)).length).toBe(2);
  await openShotSetup(page);
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('A separate alternative.');
  await expect.poll(async () => (await setups(request, id))[1].directingNotes).toBe('A separate alternative.');
  expect((await setups(request, id))[0].directingNotes).toBe('A separate alternative.');
});

test('planning, cast, coverage-only duplication, deletion and recovery in the same workspace', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const planning = page.locator('.shot-planning-dialog');
  await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Draft shots', exact: true }).click();
  await planning.getByRole('button', { name: 'Add reviewed shots', exact: true }).click();
  await expect(planning).not.toBeVisible();
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('textbox', { name: 'H3 prompt', exact: true })).toBeHidden();
  await page.locator('.shot-cast-disclosure > summary').click();
  await page.getByLabel('Add silent character').fill('Observer');
  await page.getByRole('button', { name: 'Add character', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).shots[0].characters.length).toBe(2);
  await page.getByLabel('Shot title').fill('A handwritten shot');
  await openShotSetup(page);
  await page.getByRole('textbox', { name: 'H3 prompt', exact: true }).fill('An unfinished manual prompt.');
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe('An unfinished manual prompt.');
  await shotAction(page, 'Duplicate');
  await expect.poll(async () => (await shots(request, id)).shots.length).toBe(2);
  await expect(page.getByLabel('Shot title')).toHaveValue('A handwritten shot (copy)');
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
  await openShotSetup(page);
  await expect(page.getByRole('textbox', { name: 'H3 prompt', exact: true })).toBeEmpty();
  await shotAction(page, 'Delete');
  const deletion = page.locator('.shot-delete-dialog');
  await deletion.getByRole('button', { name: /Delete 1 shot/ }).click();
  await expect(deletion).not.toBeVisible();
  await expect.poll(async () => (await shots(request, id)).shots.length).toBe(1);
  await page.locator('.shots-heading').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).shots.length).toBe(2);
});

test('navigation and concurrent browser drafts cannot overwrite a completed composition', async ({ page, context, request }) => {
  test.setTimeout(120000);
  const id = await fixture(page, request);
  await openShotSetup(page);
  await chooseModel(page);
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('SILENT_START: keep the staging clear.');
  await page.getByRole('button', { name: 'Compose prompt', exact: true }).click();
  await expect(page.getByRole('button', { name: /Writing prompt/ })).toBeVisible();
  await page.goto(`/projects/${id}`);
  await expect.poll(async () => (await setups(request, id))[0].prompt, { timeout: 15000 }).toContain('Vision-composed staging');
  const setup = (await setups(request, id))[0];
  await page.goto(`/projects/${id}/production?shotId=${setup.shotId}&setupId=${setup.id}&view=Prompt`);
  await expect(page).toHaveURL(/\/shots\?/);
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await expect(editor).toContainText('Vision-composed staging');
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('INVALID_COMPOSITION');
  await promptAssist(page);
  await page.getByRole('button', { name: 'Revise with AI', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText(/complete composition/);
  expect((await setups(request, id))[0].prompt).toBe(setup.prompt);
  await page.getByRole('button', { name: 'Clear prompt', exact: true }).click();
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('SILENT_START: another attempt.');
  await page.getByRole('button', { name: 'Compose prompt', exact: true }).click();
  await editor.fill('Keep this manual draft while the AI runs.');
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe('Keep this manual draft while the AI runs.');
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeVisible({ timeout: 15000 });
  await expect(editor).toHaveText('Keep this manual draft while the AI runs.');
  const other = await context.newPage(); await other.goto(`/projects/${id}/shots`);
  await openShotSetup(other);
  await other.getByLabel('Request options', { exact: true }).click();
  await other.getByRole('button', { name: 'New request', exact: true }).click();
  await expect(other.getByLabel('Direction for AI')).toBeVisible();
  await other.getByLabel('Direction for AI').fill('Different direction from another tab.');
  await other.getByLabel('Direction for AI').press('Tab');
  await expect.poll(async () => (await setups(request, id))[0].directingNotes).toContain('another tab');
  await page.getByRole('button', { name: 'Review changes', exact: true }).click();
  await page.locator('.prompt-review-dialog').getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(page.locator('.prompt-review-dialog').getByRole('alert')).toContainText('Since this prompt was written, the Direction for AI changed');
  expect((await setups(request, id))[0].prompt).toBe('Keep this manual draft while the AI runs.');
  await other.close();
});

test('shot tabs retain scroll while prompt edits live in the setup dialog', async ({ page, request }) => {
  const id = await fixture(page, request);
  const body = page.locator('.workspace-center .workspace-pane-body');
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  const description = 'Coverage stays in the Shot tab.\n'.repeat(15);
  await page.getByLabel('Action and camera').fill(description);
  await expect.poll(async () => (await shots(request, id)).shots[0].description).toBe(description);
  await body.evaluate(el => el.scrollTop = el.scrollHeight);
  const shotScroll = await body.evaluate(el => el.scrollTop);
  expect(shotScroll).toBeGreaterThan(50);
  await shotTab(page, 'Shot').focus(); await page.keyboard.press('ArrowRight');
  await expect(shotTab(page, 'Takes')).toBeFocused();
  await page.keyboard.press('Home'); await expect(shotTab(page, 'Shot')).toBeFocused();
  await expect.poll(() => body.evaluate(el => el.scrollTop)).toBe(shotScroll);
  await openShotSetup(page);
  await editor.fill('Keep this manually written prompt.');
  await editor.press('Control+End'); await editor.pressSequentially(' Extra ending');
  await expect.poll(async () => (await setups(request, id))[0].prompt).toContain('Extra ending');
  // Visiting the preset dialog and coming back keeps the prompt's Undo history.
  await openShotSetup(page, 'Generation settings'); await openShotSetup(page);
  await expect(editor).toContainText('Extra ending');
  await page.getByRole('button', { name: 'Undo prompt edit', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).not.toContain('Extra ending');
  await page.getByRole('button', { name: 'Redo prompt edit', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toContain('Extra ending');
  await closeShotSetup(page);
  await expect.poll(() => body.evaluate(el => el.scrollTop)).toBe(shotScroll);
  await page.reload(); await openShotSetup(page); await expect(editor).toContainText('Extra ending');
  for (const name of ['Shot', 'Takes', 'Prompt']) {
    await page.goto('/projects/' + id + '/shots?view=' + name);
    if (name === 'Prompt') await expect(editor).toBeVisible();
    else await expect(shotTab(page, name)).toHaveAttribute('aria-selected', 'true');
  }
});

test('prompt undo stays with its shot and resets when leaving the workspace', async ({ page, request }) => {
  const id = await fixture(page, request);
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  const undo = page.getByRole('button', { name: 'Undo prompt edit', exact: true });
  const redo = page.getByRole('button', { name: 'Redo prompt edit', exact: true });
  await openShotSetup(page);
  await expect(undo).toBeDisabled(); await expect(redo).toBeDisabled();
  await editor.fill('First shot prompt.');
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe('First shot prompt.');
  await closeShotSetup(page);
  await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).shots.length).toBe(2);
  await openShotSetup(page);
  await expect(editor).toBeEmpty(); await expect(undo).toBeDisabled();
  await editor.fill('Second shot prompt.');
  await expect.poll(async () => (await setups(request, id))[1].prompt).toBe('Second shot prompt.');
  await closeShotSetup(page);
  await page.locator('.shot-list-row').first().click();
  await openShotSetup(page);
  await undo.click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe('');
  expect((await setups(request, id))[1].prompt).toBe('Second shot prompt.');
  await closeShotSetup(page);
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await page.getByRole('link', { name: 'Shots', exact: true }).click();
  await openShotSetup(page);
  await expect(undo).toBeDisabled(); await expect(redo).toBeDisabled();
});

test('new shots open Shot, existing shots keep the view, and hidden composition completes safely', async ({ page, request }) => {
  const id = await fixture(page, request);
  await openShotSetup(page);
  await chooseModel(page);
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('SILENT_START: continue while I edit coverage.');
  await page.getByRole('button', { name: 'Compose prompt', exact: true }).click();
  await expect(page.getByRole('button', { name: /Writing prompt/ })).toBeVisible();
  await closeShotSetup(page); await shotTab(page, 'Shot').click();
  await expect.poll(async () => (await setups(request, id))[0].prompt, { timeout: 15000 }).toContain('Vision-composed staging');
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
  await openShotSetup(page);
  await expect(page.getByRole('textbox', { name: 'H3 prompt', exact: true })).toContainText('Vision-composed staging');
  await closeShotSetup(page); await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect.poll(async () => (await shots(request, id)).shots.length).toBe(2);
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
  await page.getByLabel('Shot title').fill('Second shot');
  await expect.poll(async () => (await shots(request, id)).shots[1].title).toBe('Second shot');
  const body = page.locator('.workspace-center .workspace-pane-body');
  await openShotSetup(page);
  await body.evaluate(el => el.scrollTop = el.scrollHeight);
  await closeShotSetup(page); await page.locator('.shot-list-row').first().click();
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
  await expect.poll(() => body.evaluate(el => el.scrollTop)).toBe(0);
  await closeShotSetup(page); await shotTab(page, 'Shot').click();
  await expect.poll(() => body.evaluate(el => el.scrollTop)).toBe(0);
  await shotTab(page, 'Takes').click();
  await page.locator('.shot-list-row').last().click();
  await expect(shotTab(page, 'Takes')).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const planning = page.locator('.shot-planning-dialog');
  await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Draft shots', exact: true }).click();
  await planning.getByRole('button', { name: 'Add reviewed shots', exact: true }).click();
  await expect(planning).not.toBeVisible();
  await expect(shotTab(page, 'Shot')).toHaveAttribute('aria-selected', 'true');
});


test('prompt diff modal: review, close, discard and apply on desktop and narrow screens', async ({ page, request }) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const id = await fixture(page, request);
  await compose(page);
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  const initial = (await setups(request, id))[0].prompt + '\n' + 'Keep the room geography and the same character identity.\n'.repeat(45);
  await editor.press('Control+A');
  await editor.evaluate((element, text) => { const data = new DataTransfer(); data.setData('text/plain', text); element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true })); }, initial);
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(initial);
  const mounted = await editor.elementHandle();
  const review = page.getByRole('button', { name: 'Review changes', exact: true });
  const dialog = page.locator('.prompt-review-dialog');
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('button', { name: 'Accept current prompt', exact: true })).toHaveCount(0);
  await promptAssist(page);
  await page.getByLabel('Direction for AI').fill('Move the camera closer.');
  await promptAssist(page);
  await page.getByRole('button', { name: 'Revise with AI', exact: true }).click();
  await expect(review).toBeVisible();
  await expect(page.locator('.composition-proposal pre')).toHaveCount(0);
  await review.click();
  await expect(dialog).toBeVisible();
  expect(await dialog.locator('.before pre').textContent()).toBe(initial);
  expect((await dialog.locator('.after ins').allTextContents()).join('')).toContain('Move the camera closer.');
  await expect(dialog.getByRole('button', { name: 'Apply changes', exact: true })).toBeInViewport();
  await expect.poll(async () => (await dialog.boundingBox()).width).toBeGreaterThan(1380);
  await dialog.locator('.mud-dialog-content').evaluate(el => el.scrollTop = 350);
  for (const side of ['Current prompt', 'Suggested prompt']) await expect(dialog.getByRole('heading', { name: new RegExp(side) })).toBeInViewport();
  await page.screenshot({ path: 'artifacts/prompt-diff-desktop.png' });
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(dialog).toBeHidden(); await expect(review).toBeFocused();
  expect((await setups(request, id))[0].prompt).toBe(initial);
  await page.setViewportSize({ width: 390, height: 844 });
  await review.click();
  await expect(dialog).toBeVisible();
  await dialog.locator('.mud-dialog-content').evaluate(el => el.scrollTop = el.scrollHeight);
  expect(await dialog.locator('.mud-dialog-content').evaluate(el => el.scrollTop)).toBeGreaterThan(100);
  for (const name of ['Close', 'Discard', 'Apply changes']) await expect(dialog.getByRole('button', { name, exact: true })).toBeInViewport();
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).focus();
  await page.keyboard.press('Tab');
  expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true);
  await page.screenshot({ path: 'artifacts/prompt-diff-narrow.png' });
  await page.keyboard.press('Escape');
  await expect(dialog).toBeHidden(); await expect(review).toBeFocused();
  await review.click(); await dialog.getByRole('button', { name: 'Discard', exact: true }).click();
  await expect(dialog).toBeHidden(); await expect(review).toHaveCount(0);
  expect((await setups(request, id))[0].prompt).toBe(initial);
  await promptAssist(page);
  await page.getByRole('button', { name: 'Revise with AI', exact: true }).click();
  await review.click();
  const proposed = await dialog.locator('.after pre').textContent();
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('button', { name: 'Prompt assistance', exact: true })).toBeFocused();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(proposed);
  expect(await editor.evaluate((element, original) => element === original, mounted)).toBe(true);
  await page.locator('.shot-setup-dialog').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await setups(request, id))[0].prompt).toBe(initial);
});


test('dialogue changes are optional review notes and do not block applying the proposed shots', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const planning = page.locator('.shot-planning-dialog');
  await page.locator('.ai-assist-dialog').getByLabel('Directing instructions (optional)').fill('DIALOGUE_VARIANT');
  await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Draft shots', exact: true }).click();
  const apply = planning.getByRole('button', { name: 'Add reviewed shots', exact: true });
  await expect(apply).toBeEnabled();
  await expect(planning.locator('.shot-proposal')).toContainText('You called me?');
  const notes = planning.locator('.planning-dialogue-notes');
  await expect(notes).toBeVisible();
  expect(await notes.getAttribute('open')).toBeNull();
  await notes.locator('summary').click();
  await expect(notes).toContainText('These notes do not prevent application');
  await expect(notes).toContainText('You called?');
  await apply.click();
  await expect(planning).toBeHidden();
  await expect.poll(async () => (await shots(request, id)).shots[0]?.dialogue[0].text).toBe('You called me?');
});

for (const narrow of [false, true]) test(`camera and editing warnings preserve acceptable shot descriptions (${narrow ? 'narrow' : 'desktop'})`, async ({page, request}) => {
  const {id} = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await page.setViewportSize({width: narrow ? 390 : 1173, height: narrow ? 844 : 1000});
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  if (narrow) {
    await page.locator('[data-toggle-pane=left]').click();
    await expect(page.locator('.workspace-left')).toBeVisible();
  }
  await page.getByRole('button', {name:'Draft shots', exact:true}).click();
  const composer = page.locator('.ai-assist-dialog');
  await composer.getByLabel('Directing instructions (optional)').fill('EDIT_AFTER_TAKE');
  await composer.getByRole('button', {name:'Draft shots', exact:true}).click();
  const planning = page.locator('.shot-planning-dialog');
  const apply = planning.getByRole('button', {name:'Add reviewed shots', exact:true});
  await expect(apply).toBeEnabled();
  const notes = planning.locator('.planning-coverage-notes');
  await expect(notes).toBeVisible();
  expect(await notes.getAttribute('open')).toBeNull();
  await notes.locator('summary').focus(); await page.keyboard.press('Enter');
  await expect(notes).toContainText('These notes do not prevent application');
  await expect(notes).toContainText('cut to');
  const description = 'End holding on the face, leaving the screenplay’s cut to black for the edit after this take.';
  await expect(planning.locator('.shot-proposal')).toContainText(description);
  expect((await shots(request,id)).shots).toHaveLength(0);
  await expect(apply).toBeInViewport();
  await planning.getByRole('button', {name:'Close',exact:true}).click();
  await expect(planning).not.toBeVisible();
  await page.getByRole('button', {name:'Review changes',exact:true}).click();
  await expect(apply).toBeEnabled();
  await apply.click();
  await expect(planning).not.toBeVisible();
  await expect.poll(async()=>(await shots(request,id)).shots[0]?.description).toBe(description);
  await page.reload();
  expect((await shots(request,id)).shots[0].description).toBe(description);
});

test('unmatched source references keep the shot and appear as review notes', async ({page, request}) => {
  const {id} = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', {name:'Draft shots', exact:true}).click();
  const composer = page.locator('.ai-assist-dialog');
  await composer.getByLabel('Directing instructions (optional)').fill('DRIFTED_SOURCE_IDS');
  await composer.getByRole('button', {name:'Draft shots', exact:true}).click();
  const planning = page.locator('.shot-planning-dialog');
  const apply = planning.getByRole('button', {name:'Add reviewed shots', exact:true});
  await expect(apply).toBeEnabled();
  const notes = planning.locator('.planning-source-notes');
  await expect(notes).toBeVisible();
  expect(await notes.getAttribute('open')).toBeNull();
  await notes.locator('summary').click();
  await expect(notes).toContainText('These notes do not prevent application');
  await expect(notes).toContainText('did not match a block in this scene');
  await expect(planning.locator('.shot-proposal')).toContainText('The camera holds while Juniper looks up');
  expect((await shots(request,id)).shots).toHaveLength(0);
  await apply.click();
  await expect(planning).not.toBeVisible();
  await expect.poll(async()=> (await shots(request,id)).shots[0]?.sourceBlockIds.length).toBeGreaterThan(0);
});
