import { cropReference, openShotSetup, toolsTab } from './workspace-tools.js';
import { test, expect } from './fixtures.js';
test.beforeEach(async ({ page }) => page.setDefaultTimeout(15000));
const state = async (request, id) => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0];
async function fixture(page, request, narrow = false) {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`); await request.post(`/fixtures/${id}/approved`); await request.post(`/fixtures/${id}/production-shot`);
  await page.goto(`/projects/${id}/shots`); await expect(page.locator('.shot-setup-summary select.generation-preset-select')).toBeVisible();
  const take = await (await request.post(`/fixtures/${id}/reference-video-take`)).json();
  const library = await (await request.post(`/fixtures/${id}/reference-reels?takeId=${take.id}`)).json();
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  await page.reload(); await toolsTab(page, 'References');
  return { id, library, editor: page.locator('.manual-reference-dialog') };
}
async function open(page) { await toolsTab(page, 'References'); await page.getByRole('button', { name: 'Manage references', exact: true }).click(); }
for (const narrow of [false, true]) test(`mixed references apply together and Undo restores both (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  test.setTimeout(90000);
  const { id, library, editor } = await fixture(page, request, narrow);
  await open(page);
  await expect(editor.locator('input[type=file]')).toHaveCount(0);
  await expect(editor.getByLabel('Existing take')).toHaveCount(0);
  const reel = library.reels[0]; const card = editor.locator(`[data-reel-id="${reel.id}"]`);
  await expect(card).toBeVisible();
  const thumbnail = card.locator('.reel-thumbnail img');
  await expect.poll(() => thumbnail.evaluate(img => img.naturalWidth)).toBeGreaterThan(0);
  await expect(card.locator('video')).toHaveCount(0);
  const thumbnailUrl = await thumbnail.getAttribute('src');
  const response = await request.get(thumbnailUrl);
  expect(response.ok()).toBe(true); expect(response.headers()['content-type']).toBe('image/jpeg');
  const cached = await request.get(thumbnailUrl, { headers: { 'If-Modified-Since': response.headers()['last-modified'] } });
  expect(cached.status()).toBe(304);
  const initial = await editor.locator('.picker-grid > [data-reel-id], .picker-grid > [data-reference]').evaluateAll(nodes => nodes.map(n => n.dataset.reelId || n.dataset.reference));
  await card.getByRole('button', { name: 'Preview ' + reel.name, exact: true }).click();
  const player = card.locator('video'); await expect.poll(() => player.evaluate(v => v.readyState)).toBeGreaterThan(0);
  await player.evaluate(v => { v.muted = true; v.currentTime = 2; }); await expect.poll(() => player.evaluate(v => v.currentTime)).toBeGreaterThanOrEqual(2);
  await expect(editor.locator('.video-reference-list > li')).toHaveCount(0);
  await editor.getByRole('button', { name: 'Reels', exact: true }).click(); await expect(editor.locator('[data-reference]')).toHaveCount(0);
  await card.locator('.add-reel').click(); await expect(card.locator('.add-reel')).toBeDisabled();
  await editor.getByRole('button', { name: 'All', exact: true }).click();
  await expect(editor.locator('[data-reference]').first()).toBeVisible();
  await page.screenshot({ path: `artifacts/unified-reference-gallery-${narrow ? 'narrow' : 'desktop'}.png` });
  await editor.getByRole('button', { name: 'Images', exact: true }).click(); await expect(editor.getByLabel('Origin', { exact: true })).toBeVisible();
  await expect(editor.locator('[data-reel-id]')).toHaveCount(0);
  const image = library.assets[0].images[0];
  await editor.locator(`[data-reference="${library.assets[0].id}/${image.id}"]`).click();
  if (narrow) await editor.getByRole('tab', { name: 'Selected references (2)', exact: true }).click();
  await cropReference(page, editor);
  await editor.getByRole('button', { name: 'Customize for this setup', exact: true }).click();
  await editor.getByLabel('Composition preservation override').fill('Keep the facial details.');
  await editor.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
  await expect(editor.getByRole('button', { name: 'Apply changes', exact: true })).toBeInViewport();
  await page.screenshot({ path: `artifacts/unified-references-${narrow ? 'narrow' : 'desktop'}.png` });
  expect((await state(request, id)).inputs.videos).toHaveLength(0);
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor).not.toBeVisible();
  const saved = await state(request, id); expect(saved.inputs.images[0].crop.width).toBe(.5); expect(saved.inputs.videos[0].media.id).toBe(reel.media.id);
  await open(page); await expect(editor.getByRole('button', { name: 'All', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(await editor.locator('.picker-grid > [data-reel-id], .picker-grid > [data-reference]').evaluateAll(nodes => nodes.map(n => n.dataset.reelId || n.dataset.reference))).toEqual(initial);
  await page.keyboard.press('Escape'); await expect(editor).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Manage references', exact: true })).toBeFocused();
  if (narrow) await page.getByRole('button', { name: 'Close Shot tools', exact: true }).click();
  await page.locator('.shots-heading').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await state(request, id)).inputs.images.length).toBe(0);
  expect((await state(request, id)).inputs.videos).toHaveLength(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('missing reel thumbnails retain preview and separate selection controls', async ({ page, request }) => {
  const { library, editor } = await fixture(page, request);
  await page.route('**/reference-videos/*/thumbnail', route => route.fulfill({ status: 404, body: '' }));
  await open(page);
  const reel = library.reels[0], card = editor.locator(`[data-reel-id="${reel.id}"]`);
  await expect(card.locator('.thumbnail-unavailable')).toBeVisible();
  await card.getByRole('button', { name: 'Preview ' + reel.name, exact: true }).click();
  await expect(card.locator('video')).toBeVisible();
  await expect(editor.locator('.video-reference-list > li')).toHaveCount(0);
  await card.locator('.add-reel').click();
  await expect(editor.locator('.video-reference-list > li')).toHaveCount(1);
});

test('failed combined save retries once and preserves immediate manual prompt edits', async ({ page, request }) => {
  const { id, library, editor } = await fixture(page, request);
  await openShotSetup(page);
  const prompt = page.getByRole('textbox', { name: 'H3 prompt', exact: true }); await prompt.fill('Manual 日本語 prompt');
  await open(page); await editor.locator('[data-reference]').first().click(); await editor.locator(`[data-reel-id="${library.reels[0].id}"] .add-reel`).click();
  await editor.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
  await request.post(`/fixtures/${id}/reference-save-failure?fail=true`);
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor.getByRole('alert')).toContainText('Fixture storage unavailable');
  expect((await state(request, id)).inputs.images).toHaveLength(0);
  await request.post(`/fixtures/${id}/reference-save-failure?fail=false`);
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor).not.toBeVisible();
  let saved = await state(request, id); expect(saved.inputs.images).toHaveLength(1); expect(saved.inputs.videos).toHaveLength(1); expect(saved.prompt).toBe('Manual 日本語 prompt');
  await page.locator('.shots-heading').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await state(request, id)).inputs.images.length).toBe(0);
  saved = await state(request, id); expect(saved.inputs.videos).toHaveLength(0); expect(saved.prompt).toBe('Manual 日本語 prompt');
});
test('changed library context stays inspectable and legacy clips survive removal from the library', async ({ page, request }) => {
  const { id, library, editor } = await fixture(page, request);
  const reel = library.reels[0]; await open(page); await editor.locator(`[data-reel-id="${reel.id}"] .add-reel`).click();
  await editor.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
  await request.post(`/fixtures/${id}/reference-reel-guidance?reelId=${reel.id}`);
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor.getByRole('alert')).toContainText('asset reel changed');
  expect((await state(request, id)).inputs.videos).toHaveLength(0); await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  await request.post(`/fixtures/${id}/legacy-reference?reelId=${reel.id}`); await page.reload(); await toolsTab(page, 'References'); await open(page);
  await expect(editor.locator(`[data-reel-id="${reel.id}"]`)).toHaveCount(0);
  await editor.locator('.video-reference-list .reference-settings-button').click(); await editor.getByLabel('Use guidance', { exact: true }).fill('Retained legacy attachment');
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor).not.toBeVisible();
  const saved = await state(request, id); expect(saved.inputs.videos[0].media.id).toBe(reel.media.id); expect(saved.inputs.videos[0].description).toBe('Retained legacy attachment');
});
test('a concurrent saved setup is not overwritten by a reference draft', async ({ page, request }) => {
  const { id, editor } = await fixture(page, request); await open(page); await editor.locator('[data-reference]').first().click();
  await request.post(`/fixtures/${id}/concurrent-reference`);
  await editor.getByRole('button', { name: 'Apply changes', exact: true }).click(); await expect(editor.getByRole('alert')).toBeVisible();
  expect((await state(request, id)).inputs.images).toHaveLength(0); expect((await state(request, id)).directingNotes).toBe('Other tab saved');
});
